// The only data file for the games hub. Adding a game = a block here. No HTML edits.
// Exactly the same shape as the apps catalogue data.js — the two are one site.
window.GAMES = [

{ key:"runner", year:"2026", flag:"🎮",
  name:{en:"3D Endless Runner", ar:"عدّاء ثلاثي الأبعاد"},
  role:{en:"Built from scratch", ar:"مبنية من الصفر"},
  one:{en:"Real 3D drawn on the GPU from Dart — no game engine", ar:"رسوم ثلاثية الأبعاد حقيقية تُرسم على بطاقة الرسوميات من Dart — دون محرك ألعاب"},
  tags:{en:["3D","Flutter GPU","flutter_scene","Web + macOS"], ar:["ثلاثية الأبعاد","Flutter GPU","flutter_scene","ويب + macOS"]},
  stats:[{v:"3D", l:{en:"real, not faked",ar:"حقيقي لا مزيف"}},
         {v:"0", l:{en:"image files",ar:"ملفات صور"}},
         {v:"3", l:{en:"lanes",ar:"حارات"}}],
  body:{en:"You control Dash on a three-lane road, dodging obstacles and collecting coins while the speed climbs. Every frame — the road, the character, the obstacles — is real 3D rendered straight to the graphics card from Dart, using flutter_scene on top of Flutter GPU. No Unity, no Unreal, not even Flame.",
        ar:"تتحكم في داش على طريق من ثلاث حارات، فتتفادى العوائق وتجمع العملات بينما تتصاعد السرعة. كل إطار في اللعبة — الطريق والشخصية والعوائق — رسوم ثلاثية الأبعاد حقيقية تُرسم مباشرة على بطاقة الرسوميات من Dart، عبر flutter_scene فوق Flutter GPU. لا Unity، ولا Unreal، ولا حتى Flame."},
  built:{en:["Scene graph, render loop and post-processing written by hand",
             "A 3D Dash imported from a .glb at runtime, with live blending between idle, run and jump",
             "Textures computed mathematically at runtime — zero image files, zero third-party licences",
             "Bloom, distance fog and colour grading at scene level",
             "Hardware instancing and a zero-allocation painter, with a frame-time meter built in",
             "An endless world from a fixed pool of road pieces"],
         ar:["مخطط المشهد وحلقة الرسم والمعالجة اللاحقة، جميعها مكتوبة يدوياً",
             "شخصية داش ثلاثية الأبعاد تُحمّل من ملف glb وقت التشغيل، مع مزج حي بين الوقوف والجري والقفز",
             "خامات محسوبة رياضياً وقت التشغيل — صفر ملفات صور وصفر تراخيص طرف ثالث",
             "توهج ضوئي وضباب مسافة وتدرج لوني على مستوى المشهد",
             "رسم بتقنية hardware instancing، ورسّام بلا تخصيص ذاكرة، ومقياس مدمج لزمن الإطار",
             "عالم لا نهائي من مجموعة ثابتة من قطع الطريق"]},
  hard:{en:"Flutter has no 3D engine. The scene graph, the render loop and the post-processing had to be written by hand, and the whole thing still has to hit the screen refresh rate.",
        ar:"لا يملك Flutter محرك رسوم ثلاثية الأبعاد. مخطط المشهد وحلقة الرسم والمعالجة اللاحقة كُتبت يدوياً، ومع ذلك يجب أن يواكب كل شيء معدل تحديث الشاشة."},
  tech:["Flutter master","Flutter GPU / Impeller","flutter_scene","Dart 3"],
  links:[{t:"run",u:"https://saqrelfirgany.github.io/flutter-scene-runner/"},
         {t:"code",u:"https://github.com/saqrelfirgany/flutter-scene-runner"}],
  icon:"",
  shots:["shots/runner-1.jpg","shots/runner-2.jpg","shots/runner-3.jpg"] },

{ key:"topple", year:"2026", flag:"🏹",
  name:{en:"Topple", ar:"توبل"},
  role:{en:"Built from scratch", ar:"مبنية من الصفر"},
  one:{en:"Bow-and-arrow physics — nothing is faked", ar:"لعبة قوس وسهم بفيزياء حقيقية — لا شيء مزيف فيها"},
  tags:{en:["2D physics","Flame","Forge2D","Box2D"], ar:["فيزياء ثنائية الأبعاد","Flame","Forge2D","Box2D"]},
  stats:[{v:"13", l:{en:"hand-built levels",ar:"مرحلة مصممة يدوياً"}},
         {v:"39", l:{en:"stars",ar:"نجمة"}},
         {v:"3", l:{en:"materials",ar:"خامات"}},
         {v:"8", l:{en:"sounds, generated",ar:"أصوات مولّدة"}}],
  body:{en:"Draw the bow, loose the arrow, topple the tower in the fewest shots. Every block has mass, friction and restitution and falls on its own — the physics is Box2D, not an animation pretending to be physics.",
        ar:"شد القوس، أطلق السهم، وأسقط البرج بأقل عدد من الطلقات. لكل مكعب كتلة واحتكاك وارتداد، وهو يسقط من تلقاء نفسه — الفيزياء هنا Box2D حقيقية، لا حركة مرسومة تتظاهر بأنها فيزياء."},
  built:{en:["13 hand-built levels, 39 stars, saved progress and a level select that unlocks as you go",
             "Three materials — wood, stone that shrugs off a hit and works as a wall, and glass that shatters and lets the arrow through",
             "Every sound generated from maths rather than recorded or licensed — eight short wavs, about 800 KB in total",
             "A trajectory preview integrated with the same gravity the physics uses, so what you aim is what you get",
             "Victory slow-motion, screen shake, debris, parallax clouds and a cinematic opening pan"],
         ar:["١٣ مرحلة مصممة يدوياً، و٣٩ نجمة، وحفظ للتقدم، وقائمة مراحل تُفتح تباعاً مع اللعب",
             "ثلاث خامات — خشب، وحجر يتحمل الضربة ويصلح جداراً، وزجاج يتحطم إلى شظايا ويخترقه السهم",
             "كل صوت مولّد رياضياً، لا مسجل ولا مرخص — ثمانية ملفات قصيرة، نحو ٨٠٠ كيلوبايت مجتمعة",
             "معاينة مسار السهم محسوبة بالجاذبية نفسها التي تعمل بها الفيزياء، فما تصوّبه هو ما يحدث",
             "بطء حركة عند الفوز، واهتزاز شاشة، وشظايا، وسُحب بحركة طبقات، ولقطة افتتاحية سينمائية"]},
  hard:{en:"The trajectory preview and the actual physics have to agree exactly. Two different gravity models would make the game feel like it lies to you.",
        ar:"معاينة المسار والفيزياء الفعلية يجب أن تتطابقا تماماً. نموذجا جاذبية مختلفان يجعلان اللعبة تبدو وكأنها تكذب عليك."},
  tech:["Flutter stable","Flame","flame_forge2d","Box2D"],
  links:[{t:"run",u:"https://saqrelfirgany.github.io/topple/"},
         {t:"code",u:"https://github.com/saqrelfirgany/topple"}],
  icon:"",
  shots:["shots/topple-1.jpg"] },

{ key:"next", year:"—", flag:"🛠️",
  name:{en:"The next one", ar:"اللعبة القادمة"},
  role:{en:"In progress", ar:"قيد التطوير"},
  one:{en:"Built in public, like the two above", ar:"تُبنى في العلن، مثل اللعبتين في الأعلى"},
  tags:{en:["Flutter","Built in public"], ar:["Flutter","بناء في العلن"]},
  stats:[],
  body:{en:"New games ship regularly, and each one is built in the open — commit by commit, with the mistakes left in. Follow along on GitHub to catch the next one from day one.",
        ar:"ألعاب جديدة تصدر باستمرار، وكل واحدة تُبنى في العلن — commit تلو الآخر، والأخطاء تبقى في مكانها. تابع على GitHub لتلحق باللعبة القادمة من يومها الأول."},
  built:{en:[], ar:[]},
  hard:{en:"", ar:""},
  tech:["Flutter"],
  links:[{t:"code",u:"https://github.com/saqrelfirgany"}],
  icon:"", shots:[], soon:true }
];

/* Text specific to the games page. The shared text is in /assets/shell.js. */
window.PAGE = {
  title:{en:"Ahmed ElFirgany — Flutter Games", ar:"أحمد الفرجاني — ألعاب Flutter"},
  tagline:{en:"Games built in Flutter. No engine.", ar:"ألعاب مبنية على Flutter. دون محرك."},
  intro:{en:"Two games running in your browser right now — a 3D endless runner drawn straight on the graphics card, and a physics game on real Box2D. Both built from scratch, in public, in Flutter.",
         ar:"لعبتان تعملان في متصفحك الآن — عدّاء ثلاثي الأبعاد يُرسم مباشرة على بطاقة الرسوميات، ولعبة فيزياء على Box2D حقيقي. كلتاهما مبنية من الصفر، في العلن، على Flutter."},
  stats:[{v:"2", l:{en:"games, playable now",ar:"لعبة تلعبها الآن"}},
         {v:"13", l:{en:"hand-built levels",ar:"مرحلة مصممة يدوياً"}},
         {v:"39", l:{en:"stars",ar:"نجمة"}},
         {v:"0", l:{en:"game engines used",ar:"محركات ألعاب"}}],
  fine:{en:"Screenshots are from the games themselves.", ar:"الصور من الألعاب نفسها."},
  cross:{
    eyebrow:{en:"The other half", ar:"النصف الآخر"},
    h:{en:"The production apps", ar:"التطبيقات التي أُطلقت فعلاً"},
    p:{en:"The games are the experiment. The catalogue is the shipped work — 15+ apps across five countries, each with the problem it solved and a store link you can open right now.",
       ar:"الألعاب هي التجربة. الكتالوج هو العمل الذي أُطلق — أكثر من ١٥ تطبيقاً في خمس دول، لكل منها المشكلة التي حلّها ورابط متجر يمكنك فتحه الآن."},
    btn:{en:"Open the app catalogue", ar:"افتح كتالوج التطبيقات"},
    to:"apps"
  }
};
