// The only data file for the games hub. Adding a game = a block here. No HTML edits.
// Exactly the same shape as the apps catalogue data.js — the two are one site.
window.GAMES = [

{ key:"runner", year:"2026", flag:"🎮",
  name:{en:"3D Endless Runner", ar:"عدّاء ثلاثي الأبعاد"},
  role:{en:"Built from scratch", ar:"مبنية من الصفر"},
  one:{en:"Real 3D from Dart, with no game engine", ar:"رسوم ثلاثية الأبعاد حقيقية من Dart، دون محرك ألعاب"},
  tags:{en:["3D","Flutter GPU","flutter_scene","Web + macOS"], ar:["ثلاثية الأبعاد","Flutter GPU","flutter_scene","ويب + macOS"]},
  stats:[{v:"3D", l:{en:"real, not faked",ar:"حقيقي لا مزيف"}},
         {v:"0", l:{en:"image files",ar:"ملفات صور"}},
         {v:"3", l:{en:"lanes",ar:"حارات"}}],
  body:{en:"You run Dash down a three-lane road. Dodge obstacles, collect coins, and the speed keeps climbing. Every frame is real 3D on the graphics card, drawn from Dart.",
        ar:"تتحكم في داش على طريق من ٣ حارات. تتفادى العوائق وتجمع العملات، والسرعة تزداد. كل إطار يُرسم بثلاثة أبعاد حقيقية على بطاقة الرسوميات، من Dart."},
  built:{en:["Scene graph, render loop and post-processing written by hand",
             "Rendered with flutter_scene on top of Flutter GPU",
             "Dash loaded from a .glb at runtime",
             "Live blending between idle, run and jump",
             "Textures computed at runtime, not loaded from images",
             "Zero image files, zero third-party licences",
             "Bloom, distance fog and colour grading at scene level",
             "Hardware instancing, zero-allocation painter, built-in frame-time meter",
             "Endless world from a fixed pool of road pieces",
             "No Unity, no Unreal, not even Flame"],
         ar:["مخطط المشهد وحلقة الرسم والمعالجة اللاحقة، كلها مكتوبة يدوياً",
             "الرسم يجري عبر flutter_scene فوق Flutter GPU",
             "شخصية داش تُحمّل من ملف glb وقت التشغيل",
             "مزج حي بين الوقوف والجري والقفز",
             "خامات محسوبة رياضياً وقت التشغيل، لا صور جاهزة",
             "صفر ملفات صور وصفر تراخيص طرف ثالث",
             "توهج ضوئي وضباب مسافة وتدرج لوني للمشهد",
             "رسم بتقنية hardware instancing، ورسّام بلا تخصيص ذاكرة",
             "مقياس مدمج لزمن الإطار",
             "عالم لا نهائي من مجموعة ثابتة من قطع الطريق",
             "لا Unity ولا Unreal ولا حتى Flame"]},
  hard:{en:"Flutter has no 3D engine. The scene graph, the render loop and the post-processing are all hand-written. It still has to hit the screen refresh rate.",
        ar:"لا يملك Flutter محرك رسوم ثلاثية الأبعاد. كتبتُ مخطط المشهد وحلقة الرسم والمعالجة اللاحقة يدوياً. ومع ذلك يجب مواكبة معدل تحديث الشاشة."},
  tech:["Flutter master","Flutter GPU / Impeller","flutter_scene","Dart 3"],
  links:[{t:"run",u:"https://saqrelfirgany.github.io/flutter-scene-runner/"},
         {t:"code",u:"https://github.com/saqrelfirgany/flutter-scene-runner"}],
  icon:"",
  shots:["shots/runner-1.jpg","shots/runner-2.jpg","shots/runner-3.jpg"] },

{ key:"topple", year:"2026", flag:"🏹",
  name:{en:"Topple", ar:"توبل"},
  role:{en:"Built from scratch", ar:"مبنية من الصفر"},
  one:{en:"Bow and arrow physics, nothing faked", ar:"قوس وسهم بفيزياء حقيقية، لا شيء مزيف"},
  tags:{en:["2D physics","Flame","Forge2D","Box2D"], ar:["فيزياء ثنائية الأبعاد","Flame","Forge2D","Box2D"]},
  stats:[{v:"13", l:{en:"hand-built levels",ar:"مرحلة مصممة يدوياً"}},
         {v:"39", l:{en:"stars",ar:"نجمة"}},
         {v:"3", l:{en:"materials",ar:"خامات"}},
         {v:"8", l:{en:"sounds, generated",ar:"أصوات مولّدة"}}],
  body:{en:"Draw the bow, loose the arrow, topple the tower in the fewest shots. Every block has mass, friction and restitution. It falls on its own, because the physics is Box2D.",
        ar:"شد القوس، أطلق السهم، وأسقط البرج بأقل عدد من الطلقات. لكل مكعب كتلة واحتكاك وارتداد. المكعبات تسقط وحدها. الفيزياء هنا Box2D، لا حركة مرسومة."},
  built:{en:["13 hand-built levels, 39 stars, saved progress",
             "Level select unlocks as you go",
             "Three materials: wood, stone and glass",
             "Stone shrugs off a hit and works as a wall",
             "Glass shatters and lets the arrow through",
             "Every sound generated from maths, not recorded or licensed",
             "Eight short wav files, about 800 KB total",
             "Trajectory preview uses the same gravity as the physics",
             "Victory slow-motion, screen shake and debris",
             "Parallax clouds and a cinematic opening pan"],
         ar:["١٣ مرحلة مصممة يدوياً، و٣٩ نجمة، وحفظ للتقدم",
             "قائمة مراحل تُفتح تباعاً مع اللعب",
             "٣ خامات: خشب وحجر وزجاج",
             "الحجر يتحمل الضربة ويصلح جداراً",
             "الزجاج يتحطم إلى شظايا ويخترقه السهم",
             "كل صوت مولّد رياضياً، لا مسجل ولا مرخّص",
             "٨ ملفات wav قصيرة، نحو ٨٠٠ كيلوبايت",
             "معاينة المسار تستخدم جاذبية الفيزياء نفسها",
             "بطء حركة عند الفوز، واهتزاز شاشة، وشظايا",
             "سُحب بحركة طبقات، ولقطة افتتاحية سينمائية"]},
  hard:{en:"The trajectory preview and the physics have to agree exactly. Two gravity models would make the game feel like it lies.",
        ar:"معاينة المسار والفيزياء الفعلية يجب أن تتطابقا تماماً. نموذجا جاذبية مختلفان يجعلان اللعبة تبدو كاذبة."},
  tech:["Flutter stable","Flame","flame_forge2d","Box2D"],
  links:[{t:"run",u:"https://saqrelfirgany.github.io/topple/"},
         {t:"code",u:"https://github.com/saqrelfirgany/topple"}],
  icon:"",
  shots:["shots/topple-1.jpg"] },

{ key:"next", year:"—", flag:"🛠️",
  name:{en:"The next one", ar:"اللعبة القادمة"},
  role:{en:"In progress", ar:"قيد التطوير"},
  one:{en:"Built in public, like the two above", ar:"تُبنى في العلن، مثل اللعبتين في الأعلى"},
  tags:{en:["Flutter","Built in public"], ar:["Flutter","بناء في العلن"]},
  stats:[],
  body:{en:"New games ship regularly. Each one is built in the open, commit by commit, mistakes left in. Follow on GitHub to catch the next one from day one.",
        ar:"ألعاب جديدة تصدر باستمرار. كل واحدة تُبنى في العلن، commit تلو الآخر، والأخطاء تبقى في مكانها. تابعني على GitHub لتلحق باللعبة القادمة من يومها الأول."},
  built:{en:[], ar:[]},
  hard:{en:"", ar:""},
  tech:["Flutter"],
  links:[{t:"code",u:"https://github.com/saqrelfirgany"}],
  icon:"", shots:[], soon:true }
];

/* Text specific to the games page. The shared text is in /assets/shell.js. */
window.PAGE = {
  title:{en:"Ahmed ElFirgany — Flutter Games", ar:"أحمد الفرجاني — ألعاب Flutter"},
  tagline:{en:"Games built in Flutter. No engine.", ar:"ألعاب مبنية على Flutter. دون محرك."},
  intro:{en:"Two games running in your browser right now. A 3D endless runner drawn straight on the graphics card. A physics game on real Box2D. Both built from scratch, in public, in Flutter.",
         ar:"لعبتان تعملان في متصفحك الآن. عدّاء ثلاثي الأبعاد يُرسم مباشرة على بطاقة الرسوميات. ولعبة فيزياء على Box2D حقيقي. كلتاهما مبنية من الصفر، في العلن، على Flutter."},
  stats:[{v:"2", l:{en:"games, playable now",ar:"لعبة تلعبها الآن"}},
         {v:"13", l:{en:"hand-built levels",ar:"مرحلة مصممة يدوياً"}},
         {v:"39", l:{en:"stars",ar:"نجمة"}},
         {v:"0", l:{en:"game engines used",ar:"محركات ألعاب"}}],
  fine:{en:"Screenshots are from the games themselves.", ar:"اللقطات من الألعاب نفسها."},
  cross:{
    eyebrow:{en:"The other half", ar:"النصف الآخر"},
    h:{en:"The production apps", ar:"تطبيقات أُطلقت فعلاً"},
    p:{en:"The games are the experiment. The catalogue is the shipped work. 15+ apps across five countries. Each one has the problem it solved and a store link.",
       ar:"الألعاب هي التجربة. الكتالوج هو العمل المنشور. أكثر من ١٥ تطبيقاً في ٥ دول. مع كل تطبيق: المشكلة وحلّها ورابط المتجر."},
    btn:{en:"Open the app catalogue", ar:"افتح كتالوج التطبيقات"},
    to:"apps"
  }
};
