// ملف الداتا الوحيد لهب الألعاب. تضيف لعبة = بلوك هنا. مفيش تعديل في الـHTML.
// نفس شكل data.js بتاع كتالوج التطبيقات بالظبط — الاتنين موقع واحد.
window.GAMES = [

{ key:"runner", year:"2026", flag:"🎮",
  name:{en:"3D Endless Runner", ar:"عدّاء ثلاثي الأبعاد"},
  role:{en:"Built from scratch", ar:"مبنية من الصفر"},
  one:{en:"Real 3D drawn on the GPU from Dart — no game engine", ar:"ثري-دي حقيقي بيترسم على كارت الشاشة من دارت — من غير محرك ألعاب"},
  tags:{en:["3D","Flutter GPU","flutter_scene","Web + macOS"], ar:["ثري-دي","Flutter GPU","flutter_scene","ويب وماك"]},
  stats:[{v:"3D", l:{en:"real, not faked",ar:"حقيقي مش مزيف"}},
         {v:"0", l:{en:"image files",ar:"ملفات صور"}},
         {v:"3", l:{en:"lanes",ar:"حارات"}}],
  body:{en:"You control Dash on a three-lane road, dodging obstacles and collecting coins while the speed climbs. Every frame — the road, the character, the obstacles — is real 3D rendered straight to the graphics card from Dart, using flutter_scene on top of Flutter GPU. No Unity, no Unreal, not even Flame.",
        ar:"بتتحكم في داش وهو بيجري في طريق بتلات حارات, بتتفادى العوائق وتجمع العملات والسرعة بتزيد. كل إطار في اللعبة — الطريق والشخصية والعوائق — ثري-دي حقيقي بيترسم على كارت الرسوميات مباشرة من دارت, بـflutter_scene فوق Flutter GPU. مفيش يونيتي, ولا أنريل, ولا حتى فليم."},
  built:{en:["Scene graph, render loop and post-processing written by hand",
             "A 3D Dash imported from a .glb at runtime, with live blending between idle, run and jump",
             "Textures computed mathematically at runtime — zero image files, zero third-party licences",
             "Bloom, distance fog and colour grading at scene level",
             "Hardware instancing and a zero-allocation painter, with a frame-time meter built in",
             "An endless world from a fixed pool of road pieces"],
         ar:["مخطط المشهد وحلقة الرسم والمعالجة البعدية كلهم مكتوبين بالإيد",
             "شخصية داش ثلاثية الأبعاد بتتحمّل من ملف glb وقت التشغيل, بمزج حي بين الوقوف والجري والقفز",
             "تكستشرات محسوبة رياضيا وقت التشغيل — صفر ملفات صور وصفر ترخيص طرف تالت",
             "بلوم وضباب مسافة وتدرج ألوان على مستوى المشهد",
             "رسم بالـinstancing ورسّام بصفر تخصيص ذاكرة, وأداة قياس أزمنة الفريمات مدمجة",
             "عالم لا نهائي من عدد ثابت من قطع الطريق"]},
  hard:{en:"Flutter has no 3D engine. The scene graph, the render loop and the post-processing had to be written by hand, and the whole thing still has to hit the screen refresh rate.",
        ar:"فلاتر مالهاش محرك ثري-دي. مخطط المشهد وحلقة الرسم والمعالجة البعدية اتكتبوا بالإيد, ومع ذلك لازم كله يلحق سرعة تحديث الشاشة."},
  tech:["Flutter master","Flutter GPU / Impeller","flutter_scene","Dart 3"],
  links:[{t:"run",u:"https://saqrelfirgany.github.io/flutter-scene-runner/"},
         {t:"code",u:"https://github.com/saqrelfirgany/flutter-scene-runner"}],
  icon:"",
  shots:["shots/runner-1.jpg","shots/runner-2.jpg","shots/runner-3.jpg"] },

{ key:"topple", year:"2026", flag:"🏹",
  name:{en:"Topple", ar:"توبل"},
  role:{en:"Built from scratch", ar:"مبنية من الصفر"},
  one:{en:"Bow-and-arrow physics — nothing is faked", ar:"لعبة قوس وسهم بفيزياء حقيقية — مفيش حاجة مزيفة"},
  tags:{en:["2D physics","Flame","Forge2D","Box2D"], ar:["فيزياء ثنائية","Flame","Forge2D","Box2D"]},
  stats:[{v:"13", l:{en:"hand-built levels",ar:"مرحلة مصممة بإيد"}},
         {v:"39", l:{en:"stars",ar:"نجمة"}},
         {v:"3", l:{en:"materials",ar:"خامات"}},
         {v:"8", l:{en:"sounds, generated",ar:"أصوات مولّدة"}}],
  body:{en:"Draw the bow, loose the arrow, topple the tower in the fewest shots. Every block has mass, friction and restitution and falls on its own — the physics is Box2D, not an animation pretending to be physics.",
        ar:"شد القوس, أطلق السهم, ووقّع البرج بأقل عدد ضربات. كل مكعب ليه كتلة واحتكاك وارتداد وبيقع لوحده — الفيزياء Box2D حقيقية, مش أنيميشن بيمثّل إنه فيزياء."},
  built:{en:["13 hand-built levels, 39 stars, saved progress and a level select that unlocks as you go",
             "Three materials — wood, stone that shrugs off a hit and works as a wall, and glass that shatters and lets the arrow through",
             "Every sound generated from maths rather than recorded or licensed — eight short wavs, about 800 KB in total",
             "A trajectory preview integrated with the same gravity the physics uses, so what you aim is what you get",
             "Victory slow-motion, screen shake, debris, parallax clouds and a cinematic opening pan"],
         ar:["١٣ مرحلة مصممة بإيد, و٣٩ نجمة, وحفظ للتقدم, وقايمة مراحل بتتفتح مع اللعب",
             "تلات خامات — خشب, وحجر بيتحمل الضربة وبيشتغل كحيطة, وقزاز بيتكسر لشظايا والسهم بيخترقه",
             "كل صوت مولّد من الرياضيات مش متسجل ولا مرخّص — تمن ملفات قصيرة, حوالي ٨٠٠ كيلوبايت كلهم",
             "معاينة مسار السهم محسوبة بنفس الجاذبية اللي الفيزياء شغالة بيها, فاللي بتصوّبه هو اللي بيحصل",
             "بطء حركة عند الفوز, واهتزاز شاشة, وشظايا, وسُحب بحركة طبقات, ولقطة افتتاحية سينمائية"]},
  hard:{en:"The trajectory preview and the actual physics have to agree exactly. Two different gravity models would make the game feel like it lies to you.",
        ar:"معاينة المسار والفيزياء الحقيقية لازم يتفقوا بالظبط. نموذجين جاذبية مختلفين بيخلوا اللعبة كأنها بتكدب عليك."},
  tech:["Flutter stable","Flame","flame_forge2d","Box2D"],
  links:[{t:"run",u:"https://saqrelfirgany.github.io/topple/"},
         {t:"code",u:"https://github.com/saqrelfirgany/topple"}],
  icon:"",
  shots:["shots/topple-1.jpg"] },

{ key:"next", year:"—", flag:"🛠️",
  name:{en:"The next one", ar:"اللي جاي"},
  role:{en:"In progress", ar:"تحت الشغل"},
  one:{en:"Built in public, like the two above", ar:"بيتبني مباشر, زي الاتنين اللي فوق"},
  tags:{en:["Flutter","Built in public"], ar:["فلاتر","بناء مباشر"]},
  stats:[],
  body:{en:"New games ship regularly, and each one is built in the open — commit by commit, with the mistakes left in. Follow along on GitHub to catch the next one from day one.",
        ar:"ألعاب جديدة بتنزل باستمرار, وكل واحدة بتتبني في العلن — كوميت ورا كوميت, والغلطات سايبها مكانها. تابع على جيت هب عشان تلحق اللي جاي من أول يوم."},
  built:{en:[], ar:[]},
  hard:{en:"", ar:""},
  tech:["Flutter"],
  links:[{t:"code",u:"https://github.com/saqrelfirgany"}],
  icon:"", shots:[], soon:true }
];

/* النص الخاص بصفحة الألعاب. المشترك في /assets/shell.js. */
window.PAGE = {
  title:{en:"Ahmed ElFirgany — Flutter Games", ar:"أحمد الفرجاني — ألعاب فلاتر"},
  tagline:{en:"Games built in Flutter. No engine.", ar:"ألعاب مبنية بفلاتر. من غير محرك."},
  intro:{en:"Two games running in your browser right now — a 3D endless runner drawn straight on the graphics card, and a physics game on real Box2D. Both built from scratch, in public, in Flutter.",
         ar:"لعبتين شغالين في متصفحك دلوقتي — عدّاء ثلاثي الأبعاد بيترسم على كارت الشاشة مباشرة, ولعبة فيزياء على Box2D حقيقي. الاتنين مبنيين من الصفر, في العلن, بفلاتر."},
  stats:[{v:"2", l:{en:"games, playable now",ar:"لعبة تلعبها دلوقتي"}},
         {v:"13", l:{en:"hand-built levels",ar:"مرحلة مصممة بإيد"}},
         {v:"39", l:{en:"stars",ar:"نجمة"}},
         {v:"0", l:{en:"game engines used",ar:"محركات ألعاب"}}],
  fine:{en:"Screenshots are from the games themselves.", ar:"الصور من اللعب نفسه."},
  cross:{
    eyebrow:{en:"The other half", ar:"النص التاني"},
    h:{en:"The production apps", ar:"التطبيقات اللي نزلت فعلا"},
    p:{en:"The games are the experiment. The catalogue is the shipped work — 15+ apps across five countries, each with the problem it solved and a store link you can open right now.",
       ar:"الألعاب هي التجربة. الكتالوج هو الشغل اللي نزل — أكتر من ١٥ تطبيق في خمس دول, كل واحد ومعاه المشكلة اللي حلها ولينك متجر تقدر تفتحه دلوقتي."},
    btn:{en:"Open the app catalogue", ar:"افتح كتالوج التطبيقات"},
    to:"apps"
  }
};
