// ملف الداتا الوحيد للكتالوج. تضيف تطبيق = بلوك هنا. مفيش تعديل في الـHTML.
window.APPS = [
{ key:"aqarmap-eg", year:"2024", flag:"🇪🇬",
  name:{en:"Aqarmap Egypt", ar:"عقارماب مصر"},
  role:{en:"Senior Flutter Developer", ar:"مطور فلاتر سنيور"},
  one:{en:"Egypt's largest real-estate marketplace", ar:"أكبر منصة عقارات في مصر"},
  tags:{en:["Real estate","Maps","Search & filters"], ar:["عقارات","خرايط","بحث وفلاتر"]},
  stats:[{v:"500K+", l:{en:"downloads",ar:"تحميل"}},{v:"200K+", l:{en:"listings",ar:"عقار معروض"}},{v:"~30%", l:{en:"faster loads",ar:"أسرع بعد التحسين"}}],
  body:{en:"A property marketplace where thousands of listings sit on a single map. I built the search engine behind it, the clustering and heat-map layer, and the performance work that cut screen-open time.",
        ar:"منصة عقارات فيها آلاف الإعلانات على خريطة واحدة. بنيت محرك البحث اللي وراها, وطبقة تجميع النقط والخرايط الحرارية, وشغل الأداء اللي قلّل وقت فتح الشاشات."},
  built:{en:["Search engine with 15+ dynamic filters","Interactive map with clustering, heat maps and neighbourhood analytics","Performance pass that cut screen-open time"],
         ar:["محرك بحث بأكتر من 15 فلتر متغير","خريطة تفاعلية بتجميع العقارات وخرايط حرارية وتحليل للأحياء","تحسين الأداء وتقليل وقت فتح الشاشات"]},
  hard:{en:"Thousands of listings on one map. Clustering plus progressive loading is what kept it smooth.",
        ar:"الليستنج بالآلاف على خريطة واحدة. الحل كان تجميع النقط وتحميل تدريجي عشان الخريطة تفضل سلسة."},
  tech:["Flutter","BLoC","Clean Architecture","Google Maps","Firebase"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.aqarmap.android"},{t:"ios",u:"https://apps.apple.com/app/id642633889"}],
  icon:"https://play-lh.googleusercontent.com/SMTnakgVfrHXtNZoeKzYELeohMgdUdTu6OcyRkgcJiAG_9JbHhLgXVBXyUxUL38E32D7NmsjiOZ9nj_PpcJdqA=w240",
  shots:["https://play-lh.googleusercontent.com/cRjxwUBdHc8o6NEFAf9cpmsVPQ8pVeYzx0sdyxpZNK2ghbB_frMJOsHC9q2E6oYJJzM6JIiSubko1fu7xcIv=w1000",
"https://play-lh.googleusercontent.com/gqsZm7xOuwgN8V6Gvh3H-OB7JJVaCh8elnpmb32a0zUeZEiSIVcjixJzgLcuBDmqDv_rJBmTELQIpeXo90ag7Q=w1000",
"https://play-lh.googleusercontent.com/xjWjOQ5rcdmxFkpMs7pllcLAHf3EdwegO_Se99fRlGPk0KGNok4lVTcB9U3zLCBVt3SE6Qg3ZzJ-FyEPncugpw=w1000",
"https://play-lh.googleusercontent.com/TqUZMzqXU_VAqKDTGqetAL0VjeEDJuMptxPFbiYqY3PoSVUGG024QNv_kR7KrjY8bC79A6v6Hd61MGYbRqOHsw=w1000",
"https://play-lh.googleusercontent.com/rBBDaIxWH3G2FlPHJweO24GZ4zWqiewBH53pP75S6jVhdLUuTaTXKAyGkqjwwEr7IMfQlN1w8rrEEi96M8ctG8o=w1000",
"https://play-lh.googleusercontent.com/eEHCFLU1UEUoB3T1e236Vs2iWI59kYg0RZ3h-Tn0titcEq9GePJpJMzQm0ui6lHgqfKEngQDTKAZ2qX7d623Kg=w1000"] },

{ key:"aqarmap-ksa", year:"2024", flag:"🇸🇦",
  name:{en:"Aqarmap KSA", ar:"عقارماب السعودية"},
  role:{en:"Senior Flutter Developer", ar:"مطور فلاتر سنيور"},
  one:{en:"The Saudi market build, localised end to end", ar:"نسخة السوق السعودي بالكامل"},
  tags:{en:["Real estate","Localisation","Government integration"], ar:["عقارات","توطين وتعريب","ربط بجهة حكومية"]},
  stats:[{v:"AR / EN", l:{en:"full bilingual",ar:"بلغتين كاملة"}},{v:{en:"Hijri",ar:"هجري"}, l:{en:"contract calendar",ar:"تقويم العقود"}}],
  body:{en:"Same foundation as the Egyptian app, different rules. Hijri dates, an investment calculator, and an integration with the Saudi Ejar platform for official rental contracts.",
        ar:"نفس أساس التطبيق المصري بقواعد مختلفة. تواريخ هجرية, وحاسبة عائد استثمار, وربط بمنصة إيجار السعودية للعقود الرسمية."},
  built:{en:["Hijri calendar for contract dates","Investment ROI calculator and currency conversion","Integration with the Saudi Ejar platform","Full bilingual UI with real RTL support"],
         ar:["تقويم هجري لتواريخ العقود","حاسبة عائد استثمار وتحويل عملات","ربط بمنصة إيجار السعودية للعقود الرسمية","واجهة بلغتين بدعم كامل لليمين لليسار"]},
  hard:{en:"One codebase, two very different markets. Separating what is shared from what is local is what made that possible.",
        ar:"كود واحد لسوقين مختلفين تماما. الفصل بين المشترك والمحلي هو اللي خلى ده ممكن من غير نسختين."},
  tech:["Flutter","BLoC","l10n","RTL","REST"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.aqarmap.invest"},{t:"ios",u:"https://apps.apple.com/app/id6470154017"}],
  icon:"https://play-lh.googleusercontent.com/Xbn_5Bzk_t7b2FoTJdMZZQhlXB7ZbaOtZACveCAgiefuqJRruydJxHvmB5JoyVS5BNKxdl_miTIGkQdO-rhsXzk=w240",
  shots:["https://play-lh.googleusercontent.com/jEFpN0vhU0_js0KV8sYCLtHDGxcEj1LA1kl-cCQ352AHeQDuPDmLhH_YHHyXAaslTOcL2ZhhhT4nb3PmeiERhw=w1000",
"https://play-lh.googleusercontent.com/rI36zphU7P2aPuwyG5HGJTN87wCECzHOPf1Ol_Ba15nVNxeM3TIyll2eWrcFahd_VryhXZHGh08FLh-PTkBj5aw=w1000",
"https://play-lh.googleusercontent.com/0fXocQ9QJNeMx6Wxq2ayDUrOFPaUgDinNjqeUx2Esqve1ln_1RY9umI-BRUHacR_Y13xQn7HpH0EXFADLaLjzPI=w1000",
"https://play-lh.googleusercontent.com/77V3pWLA1fxM73qOv4a8g8SPvkqEpeOvtdtqFA1WXfDr-C480IMiNM2Pk46KZgGsfB_yLt_LzE69W6eZGuFzi8Y=w1000",
"https://play-lh.googleusercontent.com/CxgCXmveElRCcfoN2sSRFge7Xvzh7oqrf8jrT2Me0sF5E-ijiMcP2qV1ouEQCBQjlMTBiZ5CX68I6Bgwhku1tA=w1000",
"https://play-lh.googleusercontent.com/rHH3abwafoheSKNMg90fH44Z3b5XtN3UGgwiIkmusC0yghN7d9zFuFbdBeirRg-OBv4n-gC-Ie_JMPbUIq5Gy3Q=w1000"] },

{ key:"aqarmap-crm", year:"2024", flag:"🏢",
  name:{en:"Aqarmap CRM", ar:"عقارماب CRM"},
  role:{en:"Senior Flutter Developer", ar:"مطور فلاتر سنيور"},
  one:{en:"Offline-first CRM for real-estate companies", ar:"نظام إدارة عملاء للشركات العقارية"},
  tags:{en:["CRM","Offline-first","Sync"], ar:["CRM","شغل أوفلاين","مزامنة"]},
  stats:[{v:"100K+", l:{en:"leads / month",ar:"عميل محتمل شهريا"}},{v:"5", l:{en:"pipeline stages",ar:"مراحل المبيعات"}}],
  body:{en:"Agents work in places with no coverage. The app writes to a local database and a sync queue pushes everything up when the network returns, without losing a single edit.",
        ar:"المندوب بيشتغل في مناطق من غير تغطية. التطبيق بيكتب في قاعدة بيانات محلية وطابور مزامنة بيرفع كل حاجة لما النت يرجع من غير ما يضيع أي تعديل."},
  built:{en:["Five-stage sales pipeline","Offline-first architecture with a sync queue","Live notifications, calendar sync and automatic follow-ups","Analytics dashboard with conversion rates"],
         ar:["مسار مبيعات من 5 مراحل","معمارية تشتغل أوفلاين أولا مع طابور مزامنة","إشعارات لحظية وتزامن مع التقويم ومتابعات أوتوماتيك","لوحة تحليلات بمعدلات التحويل"]},
  hard:{en:"Conflicts. Two devices editing the same lead offline had to resolve deterministically, not last-write-wins.",
        ar:"التعارض. جهازين بيعدلوا نفس العميل وهما أوفلاين لازم يتحلوا بشكل محدد, مش آخر واحد يكتب يكسب."},
  tech:["Flutter","SQLite","Offline-first","Firebase Messaging","Background Services"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.project.aqarmap.crm"},{t:"ios",u:"https://apps.apple.com/app/id1271197604"}],
  icon:"https://play-lh.googleusercontent.com/yELBszBts6idqTepQho3gjHGW0PbotZlybNr0Uf7v9dn-P7CDycypK4-4yl76ly1X5yGYNfrU6GphreVLYB0=w240",
  shots:["https://play-lh.googleusercontent.com/1NSYRhxDm1Cqhe9V7D8akGARmARAzFx0ziSHClXaCTHOgISPKD-f_WPmrZd_-NqdK7Axo15Ui8EW0QKSjUhEAQ=w1000",
"https://play-lh.googleusercontent.com/uuMKiRCPh4dev-nUef-0CFs2SPhYAvoN0stsZUorq8IUwrhwtMlLxYL_CucgMEAt8Yr1OskW-T46WjoMXilf4Io=w1000",
"https://play-lh.googleusercontent.com/qX8UVvyGjX_acjgysMgqwZXrfEmm_0ATS4Ps_K9-UvoEq6J-QFWTAHLQPodSLU9DT7qH5xyVegdwhQTPvm6T=w1000",
"https://play-lh.googleusercontent.com/lmTsmOqs8nqlpWTzMCsB6HI9M0BNntuUmSh5UueHkjXEynaxPsWf-6ATdHEJrz2dUkdCvSnNIezYFcMpYgaJsA=w1000"] },

{ key:"adam", year:"2022", flag:"🇸🇦",
  name:{en:"Adam Pharmacy", ar:"صيدلية آدم"},
  role:{en:"Flutter Developer & Team Lead", ar:"مطور فلاتر وقائد فريق"},
  one:{en:"Online pharmacy with prescription scanning", ar:"صيدلية أونلاين بقراءة الروشتة"},
  tags:{en:["Healthcare","Delivery","OCR"], ar:["صحة","توصيل","قراءة صور"]},
  stats:[{v:"10K+", l:{en:"downloads",ar:"تحميل"}},{v:"3", l:{en:"devs led",ar:"مطورين تحت قيادتي"}}],
  body:{en:"Customers photograph a handwritten prescription and the app reads it. I led a team of three on this one, and the reading pipeline was the part that decided whether the product worked at all.",
        ar:"العميل بيصوّر روشتة مكتوبة بخط اليد والتطبيق بيقراها. قدت فريق من تلاتة على ده, ومسار القراءة كان هو اللي بيقرر المنتج هيشتغل أصلا ولا لأ."},
  built:{en:["Prescription reading through the camera","Live order tracking","Medication reminders","Payment gateway and notifications"],
         ar:["قراءة الروشتة بالكاميرا","تتبع الطلب لحظيا","تذكير بمواعيد الدوا","ربط بوابة دفع وإشعارات"]},
  hard:{en:"Handwriting. Image pre-processing before reading, plus a human confirmation step before the order goes through — a wrong medicine is not a bug you can ship.",
        ar:"الخط اليدوي. معالجة الصورة قبل القراءة, وخطوة تأكيد بشري قبل ما الطلب يعدي — دوا غلط مش باج ينفع يعدي."},
  tech:["Flutter","Firebase","OCR","Payment Gateway","Google Maps"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.adampharmacy"},{t:"ios",u:"https://apps.apple.com/app/id1672276218"}],
  icon:"https://play-lh.googleusercontent.com/r01GfpnAxEShNXIHee2gibLe-fMM56JBBQZhzcX22T0yQ1LQlA8w5EwNBZPtexzbpYI_mYVhLw0aGEODXRtB=w240",
  shots:["https://play-lh.googleusercontent.com/ZgpsLb3krfungshYUz_GoVqVu3RJ3OOKZQXGW-7cbjoDzRoU006S7Vwxqzuhg08Hp-jQTlFmL7YFNfANgonG=w1000",
"https://play-lh.googleusercontent.com/xGyl16_IxFC82fvxtE2RrcZF9916Zd-ZnuDobj6-Q6TPGBIRc5tdefzePtPXXFzaTvrcXdCmY-Q1ezjnNx5-iQ=w1000",
"https://play-lh.googleusercontent.com/OjEywH7XhKWhkLcKeiD0jzzDUPS33YnhspWsEeDZRFMXlmNqU6hnv6-UOgGOoc0WRjGSNskqf4MMPeHTNrYer0c=w1000",
"https://play-lh.googleusercontent.com/LiUQSIRyRxcB-YF39YJShyq7Qt6YpvH_geO9W0nSfvVCpT115NTr6amxQDDSoCHb-V1anTfTF-c_c3Tpu7awPGA=w1000",
"https://play-lh.googleusercontent.com/kL6JNt2LxRpK-cpE55jWVPaFzQmQTx3VXEGvpcTTTiWNl6o2HW8fRud7-1Y9-9jt1pq5rxczQGDbUHEsoPWY=w1000"] },

{ key:"bizbura", year:"2022", flag:"🇹🇷",
  name:{en:"BizBuradayız", ar:"بيز بورادايز"},
  role:{en:"Flutter Developer", ar:"مطور فلاتر"},
  one:{en:"Two-sided on-demand services platform", ar:"منصة خدمات عند الطلب بتطبيقين"},
  tags:{en:["On-demand","Live tracking","Two apps"], ar:["خدمات عند الطلب","تتبع لحظي","تطبيقين"]},
  stats:[{v:"2", l:{en:"apps, one system",ar:"تطبيق في نظام واحد"}},{v:{en:"Live",ar:"لحظي"}, l:{en:"map tracking",ar:"تتبع على الخريطة"}}],
  body:{en:"A customer app and a provider app that have to agree on the same state in the same second. Turkey-wide, covering home, beauty, car and delivery services.",
        ar:"تطبيق للعميل وتطبيق لمزود الخدمة لازم يتفقوا على نفس الحالة في نفس الثانية. في تركيا كلها, وبيغطي خدمات البيت والتجميل والسيارات والتوصيل."},
  built:{en:["A complete system across two apps","Instant matching between customer and nearest provider","Live location tracking on the map","In-app chat and real-time order updates","Photo reviews"],
         ar:["نظام كامل من تطبيقين","مطابقة فورية بين العميل وأقرب مزود خدمة","تتبع لحظي للموقع على الخريطة","شات داخل التطبيق وتحديثات لحظية","تقييمات بصور"]},
  hard:{en:"Two apps, one truth. Pusher with a single state layer is what stopped them drifting apart.",
        ar:"تطبيقين وحقيقة واحدة. Pusher مع طبقة حالة واحدة هو اللي منعهم يفترقوا."},
  tech:["Flutter","BLoC","Pusher","Google Maps","Real-time Tracking"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.bizburadayiz",label:{en:"Customer app",ar:"تطبيق العميل"}},
         {t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.bizburadayiz.driver",label:{en:"Provider app",ar:"تطبيق مزود الخدمة"}}],
  icon:"https://play-lh.googleusercontent.com/V6df11qDA0Y-Wo1eY4KAbzd5QnGtC13OmHLRKN2sI-VMdWt_jG9v3gPVlljxFjsnMlyxbhI87FflayM76pnpcIM=w240",
  shots:["https://play-lh.googleusercontent.com/Q3BaS6DWURTUvmD8ikJKsHZnaQo6JBhEi2-7CVBqwjiSnWy6BxHyrI40Gg09T96CQNh3xqXJ2mFs6HsfkeWECw=w1000",
"https://play-lh.googleusercontent.com/QEwCQQwvwmeEjhqUBDrjWseSqrucIFbwvF1tRAN34PUgHiiUSf2NF_dYlmvn7khEgy_1MrQP-K_XIu5VeMQNCg=w1000",
"https://play-lh.googleusercontent.com/9mepB9E6CuC0OEQE5cpC6UXF5c-PzD4rHhSjGdZz95u4G61D6llqCGopZbCvPfcdHt6W42UkADza3G0ziD6v=w1000",
"https://play-lh.googleusercontent.com/DjzSxxpDKar6qLgWpg3enxPPQxI6GFO_sAc2FqyLBVE-4NvuLyp2qMLOMX5ijkUwfHGQlosGz3NL58MPQrJ35w=w1000",
"https://play-lh.googleusercontent.com/Xc4G7CXdwhV3XnGWjWRCaGgfZPtVhhkik86kdLMSihU6-xceHQUgwQ9MapYaToiBEzG9c6lX1B664YHNSNUJbQ=w1000",
"https://play-lh.googleusercontent.com/gcRVkt-yqmrU8E9uU-DonU8gE6QLus3IypAbHf3lTGxwVRoKqaNro0F2DnCldAWc18fKKPMYdUO2bu8cTDbsrw=w1000"] },

{ key:"alnasser", year:"2022", flag:"🇰🇼",
  name:{en:"ALNASSER", ar:"الناصر"},
  role:{en:"Flutter Developer", ar:"مطور فلاتر"},
  one:{en:"Kuwaiti fashion and sports retail", ar:"متجر أزياء ورياضة كويتي"},
  tags:{en:["E-commerce","Loyalty","Deep linking"], ar:["متجر إلكتروني","نقاط ولاء","روابط تسويق"]},
  stats:[{v:{en:"Loyalty",ar:"ولاء"}, l:{en:"points system",ar:"نظام نقاط"}},{v:{en:"Deep",ar:"عميقة"}, l:{en:"campaign links",ar:"روابط الحملات"}}],
  body:{en:"A retail app where the marketing campaigns had to land people directly on a product, not on a home screen. Deep linking is what moved the conversion number.",
        ar:"تطبيق متجر كانت الحملات التسويقية فيه لازم توصّل الناس للمنتج مباشرة مش للصفحة الرئيسية. الروابط العميقة هي اللي حركت رقم التحويل."},
  built:{en:["Catalogue with advanced filtering and a size guide","Loyalty points and member-only discounts","Multiple payment methods at checkout","Deep links for marketing campaigns"],
         ar:["كتالوج بفلترة متقدمة ودليل مقاسات","نقاط ولاء وخصومات للأعضاء","دفع بأكتر من طريقة","روابط عميقة لحملات التسويق"]},
  hard:{en:"Getting a campaign click to open the exact product inside the app, whether the app was installed or not.",
        ar:"إن ضغطة على إعلان تفتح المنتج نفسه جوه التطبيق, سواء التطبيق متسطب ولا لأ."},
  tech:["Flutter","Provider","Deep Linking","Payment","Firebase Analytics"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.alnasser"}],
  icon:"https://play-lh.googleusercontent.com/UAh109EbkFdE4tJNM_oWhxwsRnX1TbdIxScZkWML5dTWEzSBRfkAnqetrr6uvR_i61pdIkrvLB9PwNs1bhV3wA=w240",
  shots:["https://play-lh.googleusercontent.com/67vbk5ytrzBWgFD_8Y4SEeGWeTo5jhDeK5HA9mVAwMFInmP9OE5Ur5cyUQkufikULSD62TY8oWXsMEx5A-bNjg=w1000",
"https://play-lh.googleusercontent.com/MJKb7bgO9eMAU-Ez_EB2ah7w5BSrgpdH9Phfrlu_wMwXz8naHhPxIWx7j_Au1nuiX-gGP2lcKDEuBltKygh6sA=w1000",
"https://play-lh.googleusercontent.com/7-uDohTXv5SZYApY3muJ5qNELez3wT4V2ck-DIP9zGlk4zdZ1OntfG24q3P5OYONt7be_Q1TOoFGNl-juBIszg=w1000",
"https://play-lh.googleusercontent.com/PQ0K-l75JtTZbd6YK0LPnBKUari3J9nNyzMBsy1qkAXFanRS_JACINgRWKSo6pH8AxazZGLcRb7yvY5l7igD=w1000",
"https://play-lh.googleusercontent.com/vVea8RTvThhk3us3cK3jwr7MXpgB0Mba5K0GqLpwA5ogeHmzjOpRwsUKqwOVLNcdyeZ451REiG1YICfqZcuq7jA=w1000"] },

{ key:"hr-portal", year:"2023", flag:"🇸🇦",
  name:{en:"Employee Self-Service Portal", ar:"بوابة موظفين"},
  role:{en:"Senior Flutter Developer", ar:"مطور فلاتر سنيور"},
  one:{en:"Self-service portal for employees", ar:"بوابة خدمة ذاتية للموظفين"},
  tags:{en:["HR","Biometric auth","Tablet + mobile"], ar:["موارد بشرية","دخول ببصمة","تابلت وموبايل"]},
  stats:[{v:{en:"Mobile + tablet",ar:"موبايل وتابلت"}, l:{en:"one build",ar:"بناء واحد"}},{v:{en:"From scratch",ar:"من الصفر"}, l:{en:"built",ar:"اتبنى"}}],
  body:{en:"An HR app for a Saudi organisation — leave, payroll, attendance and document requests, all self-service. Clean architecture from the first line, and one interface that adapts to phone and tablet.",
        ar:"تطبيق موارد بشرية لجهة سعودية — إجازات ومسيرات ورواتب وحضور وانصراف وطلبات مستندات, كلها خدمة ذاتية. معمارية نظيفة من أول سطر, وواجهة واحدة بتتظبط على الموبايل والتابلت."},
  built:{en:["Clean architecture from the first line","One interface that adapts to phone and tablet","Face and fingerprint sign-in","Leave, payroll, attendance and document requests"],
         ar:["معمارية نظيفة من أول سطر","واجهة واحدة بتتظبط على الموبايل والتابلت","دخول ببصمة الوجه والإصبع","إجازات ومسيرات ورواتب وحضور وانصراف وطلبات مستندات"]},
  hard:{en:"The same app had to work on phone and tablet at the same quality. Real responsive design, not a stretched screen.",
        ar:"نفس التطبيق لازم يشتغل على موبايل وتابلت بنفس الجودة. تصميم متجاوب حقيقي مش تكبير شاشة."},
  tech:["Flutter","Clean Architecture","Biometric Auth","Secure Storage","l10n"],
  links:[], internal:true,
  icon:"", shots:[] },
{ key:"pm-tablet", year:"2023", flag:"🇸🇦",
  name:{en:"Project Management Platform", ar:"منصة إدارة مشاريع"},
  role:{en:"Senior Flutter Developer", ar:"مطور فلاتر سنيور"},
  one:{en:"Project management for contracting firms", ar:"إدارة مشاريع لشركات المقاولات"},
  tags:{en:["Project management","Tablet-first","Offline"], ar:["إدارة مشاريع","تابلت أولا","شغل أوفلاين"]},
  stats:[{v:{en:"Tablet-first",ar:"تابلت أولا"}, l:{en:"designed for",ar:"مصممة له"}},{v:{en:"Offline",ar:"أوفلاين"}, l:{en:"works on site",ar:"شغال في الموقع"}}],
  body:{en:"A project management platform for contracting and engineering firms. Interactive Gantt charts, live collaboration, and an offline mode for construction sites with no coverage.",
        ar:"منصة إدارة مشاريع لشركات المقاولات والهندسة. مخططات جانت تفاعلية, وتعاون لحظي, ووضع أوفلاين لمواقع البناء اللي من غير تغطية."},
  built:{en:["Interactive Gantt charts","Live collaboration over WebSocket","Offline mode for use on construction sites","Project files and drawings management"],
         ar:["مخططات جانت تفاعلية","تعاون لحظي على WebSocket","وضع أوفلاين للاستخدام في مواقع البناء","إدارة ملفات ومخططات المشروع"]},
  hard:{en:"A Gantt chart with hundreds of tasks on a tablet needed custom painting to stay smooth. An off-the-shelf library was not going to do it.",
        ar:"مخطط جانت على تابلت بمئات المهام محتاج رسم مخصص عشان يفضل سلس. مكتبة جاهزة ما كانتش هتنفع."},
  tech:["Flutter","Custom Widgets","WebSockets","Offline-first"],
  links:[], internal:true,
  icon:"", shots:[] },
{ key:"bhr", year:"2021", flag:"🇦🇪",
  name:{en:"Bhr", ar:"بحر"},
  role:{en:"Flutter Developer", ar:"مطور فلاتر"},
  one:{en:"Marine services and activities platform", ar:"منصة خدمات وأنشطة بحرية"},
  tags:{en:["Booking","Rentals","Maps"], ar:["حجوزات","تأجير","خرايط"]},
  stats:[{v:{en:"Server",ar:"السيرفر"}, l:{en:"holds the slot",ar:"هو اللي بيحجز"}},{v:{en:"Custom",ar:"مخصصة"}, l:{en:"animations",ar:"حركات"}}],
  body:{en:"Diving trips, fishing charters, boat and equipment rental. The booking system had to confirm a slot on the server, never on the phone, or two people end up on the same boat.",
        ar:"رحلات غطس وصيد وتأجير قوارب ومعدات. نظام الحجز لازم يأكد الميعاد على السيرفر مش على التليفون, وإلا اتنين يلاقوا نفسهم على نفس المركب."},
  built:{en:["Trip booking calendar","Equipment rental system","Interactive map of diving spots","Custom animations"],
         ar:["تقويم حجز رحلات","نظام تأجير معدات","خريطة مواقع الغطس","حركات مخصصة"]},
  hard:{en:"Double booking. The availability check has to be the server's decision, not the client's.",
        ar:"الحجز المزدوج. التأكد إن الميعاد فاضي قرار السيرفر مش قرار التطبيق."},
  tech:["Flutter","Custom Animations","Google Maps","REST"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.ebtasm.bhr"}],
  icon:"", shots:[] },

{ key:"yseer", year:"2025", flag:"🇸🇦",
  name:{en:"Yseer", ar:"يسير"},
  role:{en:"Senior Flutter Developer", ar:"مطور فلاتر سنيور"},
  one:{en:"Saudi ordering and delivery platform", ar:"منصة سعودية للطلب والتوصيل"},
  tags:{en:["Logistics","Real-time","Payments"], ar:["لوجستيك","لحظي","مدفوعات"]},
  stats:[{v:{en:"Riyadh",ar:"الرياض"}, l:{en:"operating city",ar:"مدينة التشغيل"}},{v:{en:"Events",ar:"الأحداث"}, l:{en:"ordered, not raced",ar:"مرتبة مش متسابقة"}}],
  body:{en:"Order state changes from several places at the same moment. Documenting and ordering the events is what stopped them colliding.",
        ar:"حالة الطلب بتتغير من كذا مكان في نفس اللحظة. توثيق الأحداث وترتيبها هو اللي منع التعارض."},
  built:{en:["Returns and financial transactions module","Documented real-time events over WebSocket and Pusher","Rebuilt booking and order routes"],
         ar:["موديول المرتجعات والمعاملات المالية","توثيق أحداث لحظية على WebSocket و Pusher","إعادة هيكلة مسارات الحجز والطلبات"]},
  hard:{en:"Concurrent state writes from multiple sources on the same order.",
        ar:"كتابة الحالة من أكتر من مصدر على نفس الطلب في نفس الوقت."},
  tech:["Flutter","BLoC","REST","WebSocket / Pusher"],
  links:[], internal:true,
  icon:"", shots:[] }
];

/* النص الخاص بصفحة التطبيقات. المشترك (الاسم, البروفايلات, البار,
   الفوتر) في /assets/shell.js — متكتبش حاجة منه هنا تاني. */
window.PAGE = {
  title:{en:"Ahmed ElFirgany — App Catalogue", ar:"أحمد الفرجاني — كتالوج التطبيقات"},
  tagline:{en:"Apps that shipped, and are still running.", ar:"تطبيقات نزلت فعلا, ولسه شغالة."},
  intro:{en:"15+ apps across five countries, 600K+ downloads on Google Play alone. Below is the work itself — every app, what it does, the hard part, and a link you can open right now.",
         ar:"أكتر من ١٥ تطبيق في خمس دول, وأكتر من ٦٠٠ ألف تحميل على جوجل بلاي لوحدها. تحت الشغل نفسه — كل تطبيق, بيعمل إيه, والجزء الصعب فيه, ولينك تقدر تفتحه دلوقتي."},
  stats:[{v:"15+", l:{en:"apps",ar:"تطبيق"}},{v:"600K+", l:{en:"downloads",ar:"تحميل"}},
         {v:"5", l:{en:"countries",ar:"دول"}},{v:"5+", l:{en:"years",ar:"سنين خبرة"}}],
  fine:{en:"Screenshots come from the public store listings.", ar:"الصور من صفحات التطبيقات على المتاجر."},
  cross:{
    eyebrow:{en:"The other half", ar:"النص التاني"},
    h:{en:"The games", ar:"الألعاب"},
    p:{en:"The apps above are the shipped work. The games are where I push Flutter past what it is supposed to do — real 3D drawn on the GPU, and real Box2D physics, both playable in your browser right now.",
       ar:"التطبيقات اللي فوق هي الشغل اللي نزل. الألعاب هي المكان اللي بدفع فيه فلاتر لأبعد من اللي المفروض تعمله — ثري-دي حقيقي بيترسم على كارت الشاشة, وفيزياء Box2D حقيقية, والاتنين تلعبهم من متصفحك دلوقتي."},
    btn:{en:"Open the games", ar:"افتح الألعاب"},
    to:"games"
  }
};
