// The only data file for the catalogue. Adding an app = a block here. No HTML edits.
window.APPS = [
{ key:"dacttra-clinic", year:"2026", flag:"🇪🇬",
  name:{en:"Dacttra — Clinic Management", ar:"دكترا — إدارة العيادات"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"The app clinic staff run the day on", ar:"التطبيق الذي يدير به فريق العيادة يومه"},
  tags:{en:["Healthcare","Roles and permissions","Billing"], ar:["رعاية صحية","أدوار وصلاحيات","فوترة"]},
  stats:[{v:"203", l:{en:"feature modules",ar:"وحدة"}},{v:"186", l:{en:"API endpoints",ar:"نداء API"}},{v:"280", l:{en:"tests",ar:"اختبار"}}],
  body:{en:"Clinic staff book appointments, open patient records, and take payment from the phone. Owners manage branches and subscriptions.",
        ar:"فريق العيادة يحجز المواعيد ويفتح ملفات المرضى ويحصّل المدفوعات من الجوال. والمالك يدير الفروع والاشتراكات."},
  built:{en:["Appointments, a day board and a waiting list","Patient records, billing and payments","Access control across 17 modules and 5 actions","Branches, services and subscriptions"],
         ar:["المواعيد ولوحة اليوم وقائمة الانتظار","ملفات المرضى والفوترة والمدفوعات","صلاحيات على ١٧ وحدة و٥ أفعال","الفروع والخدمات والاشتراكات"]},
  hard:{en:"Switching role or branch changes what the whole app may read and write. One permission source, read by every screen, with no restart.",
        ar:"تغيير الدور أو الفرع يغيّر ما يستطيع التطبيق كله قراءته وكتابته. مصدر صلاحيات واحد تقرأ منه كل شاشة, بلا إعادة تشغيل."},
  tech:["Flutter","Clean Architecture","BLoC","GetIt","Dio","RBAC","PDF"],
  links:[{t:"ios",u:"https://apps.apple.com/us/app/id6763802371"}],
  icon:"https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/f6/73/61/f67361a6-cf29-5ad7-375f-894e84ea47cf/AppIcon-0-1x_U007epad-0-11-0-85-220-0.png/512x512bb.jpg",
  shots:["https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/00/42/5e/00425e65-e88a-96a6-26b9-7bf24d8e3935/Screenshots_ar_4.jpg/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/ba/ef/4e/baef4e89-7c10-3831-804e-c206bc7b5d26/Screenshots_half_en_1.jpg/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/97/44/9f/97449f2f-a74f-0750-b79d-a18ae5780438/Screenshots_half_en2.jpg/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/66/4b/b2/664bb2e9-f78f-9e0a-6b1e-e0fd1bf2976b/Screenshots_IN_1_ar.jpg/320x480bb.jpg"] },

{ key:"dacttra-patient", year:"2025", flag:"🇪🇬",
  name:{en:"Dacttra: Your Health Partner", ar:"دكترا — تطبيق المرضى"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Find a doctor or a clinic, and book an appointment", ar:"ابحث عن طبيب أو مركز, واحجز موعداً"},
  tags:{en:["Healthcare","Booking","Search"], ar:["رعاية صحية","حجز","بحث"]},
  stats:[{v:"51", l:{en:"API endpoints",ar:"نداء API"}},{v:"56", l:{en:"tests",ar:"اختبار"}}],
  body:{en:"Patients search by specialty and area, read ratings, and book against the times a clinic actually has free.",
        ar:"المريض يبحث بالتخصص والمنطقة, ويقرأ التقييمات, ويحجز على المواعيد المتاحة فعلاً لدى العيادة."},
  built:{en:["Search by specialty, area and rating","Booking against live availability","A profile for every doctor and centre"],
         ar:["بحث بالتخصص والمنطقة والتقييم","حجز على المواعيد المتاحة فعلاً","ملف لكل طبيب ومركز"]},
  hard:{en:"The same slot is visible to many patients at once. The check that it is still free happens on the server, never on the phone.",
        ar:"الموعد نفسه يظهر لعدة مرضى في اللحظة ذاتها. التأكد من أنه ما زال متاحاً يتم على الخادم, لا على الجوال."},
  tech:["Flutter","Clean Architecture","BLoC","Dio","Firebase"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.dacttra.platform"},{t:"ios",u:"https://apps.apple.com/us/app/id6756008573"}],
  icon:"https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/27/20/3e/27203ed7-3a2f-5c1a-a52c-ebc766c17e4e/AppIcon-0-1x_U007epad-0-11-0-85-220-0.png/512x512bb.jpg",
  shots:["https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/49/ac/7e/49ac7edc-ccad-176a-c334-4a9174160841/Simulator_Screenshot_-_iPhone_14_Pro_Max_-_2025-12-08_at_13.53.36.png/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/d2/42/5e/d2425e46-695b-817d-cc9f-5242f751e088/Simulator_Screenshot_-_iPhone_14_Pro_Max_-_2025-12-08_at_13.53.53.png/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/fc/44/17/fc441755-9426-e98a-d731-993404d819e6/Simulator_Screenshot_-_iPhone_14_Pro_Max_-_2025-12-08_at_13.54.11.png/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/e7/32/e3/e732e329-b1d7-50f8-e97f-60701e715a95/Simulator_Screenshot_-_iPhone_15_Pro_Max_-_2025-12-10_at_15.19.26.png/320x480bb.jpg"] },

{ key:"kronos", year:"2025", flag:"🌍",
  name:{en:"KronosPay", ar:"كرونوس باي"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Attendance, rostering and payroll in one app", ar:"حضور ومناوبات ورواتب في تطبيق واحد"},
  tags:{en:["Workforce","Works with no signal","Geofencing"], ar:["قوى عاملة","يعمل بلا شبكة","نطاق جغرافي"]},
  stats:[{v:"50", l:{en:"API endpoints",ar:"نداء API"}},{v:"94", l:{en:"tests",ar:"اختبار"}},{v:{en:"Offline",ar:"بلا شبكة"}, l:{en:"punch queue",ar:"طابور تسجيل"}}],
  body:{en:"Teams clock in and out on site or remotely. Managers build rosters, and payroll reads the result.",
        ar:"الفريق يسجّل حضوره وانصرافه في الموقع أو عن بُعد. والمدير يبني المناوبات, والرواتب تقرأ النتيجة."},
  built:{en:["Clock in and out with location and photo","Rosters, schedules and leave balances","A site radius set on the server","A punch queue that survives no signal"],
         ar:["تسجيل حضور وانصراف بالموقع والصورة","المناوبات والجداول وأرصدة الإجازات","نطاق الموقع محدّد من الخادم","طابور تسجيل يصمد بلا شبكة"]},
  hard:{en:"A punch is a payroll record. It cannot be lost, duplicated, or timed by a clock the user controls.",
        ar:"التسجيلة سجل رواتب. لا يصح أن تضيع أو تتكرر أو يحدد وقتها ساعة يتحكم فيها المستخدم."},
  tech:["Flutter","SQLite","WorkManager","Geofencing","Offline-first","BLoC"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.innovative.kronospay"},{t:"ios",u:"https://apps.apple.com/us/app/id6755912599"}],
  icon:"https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/27/38/83/27388319-6241-19a2-bb9c-1b7811b03e68/AppIcon-0-1x_U007epad-0-11-0-85-220-0.png/512x512bb.jpg",
  shots:["https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/d5/94/c8/d594c8f1-5f07-02e2-ad6c-d3d9a196046e/Simulator_Screenshot_-_iPhone_14_Pro_Max_-_2025-12-08_at_13.38.13.png/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/1d/06/ab/1d06ab12-5afd-df0f-f68b-64bc87b4a7fd/Simulator_Screenshot_-_iPhone_14_Pro_Max_-_2025-12-08_at_13.32.14.png/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource211/v4/af/49/0a/af490a6d-5959-0084-390f-cd80f6670b26/Simulator_Screenshot_-_iPhone_14_Pro_Max_-_2025-12-08_at_13.38.47.png/320x480bb.jpg",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource221/v4/77/d8/75/77d87501-c5af-a59d-9bf5-a917bdbf4ee2/Simulator_Screenshot_-_iPhone_15_Pro_Max_-_2025-12-14_at_13.31.39.png/320x480bb.jpg"] },

{ key:"aqarmap-eg", year:"2024", flag:"🇪🇬",
  name:{en:"Aqarmap Egypt", ar:"عقارماب مصر"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Property marketplace for home buyers in Egypt", ar:"منصة عقارات لمشتري البيوت في مصر"},
  tags:{en:["Real estate","Map search","Filters"], ar:["عقارات","بحث على الخريطة","فلاتر"]},
  stats:[{v:"500K+", l:{en:"downloads",ar:"تحميل"}},{v:"4.6★", l:{en:"from 6.1K ratings",ar:"من ٦١٠٠ تقييم"}},{v:"200K+", l:{en:"listings",ar:"عقار معروض"}},{v:"~30%", l:{en:"faster screen loads",ar:"أسرع في فتح الشاشة"}}],
  body:{en:"House hunters browse listings on a single live map. The platform draws about two million visitors a month.",
        ar:"الباحث عن سكن يتصفح الإعلانات على خريطة واحدة. المنصة تستقبل نحو مليوني زائر شهرياً."},
  built:{en:["Search with 15+ dynamic filters","Live map with clustering and heat maps","Neighbourhood analytics on the map","A performance pass on screen-open time"],
         ar:["بحث بأكثر من ١٥ فلتراً متغيراً","خريطة حية بتجميع النقاط وخرائط حرارية","تحليلات الأحياء على الخريطة","تحسين أداء يقلّل زمن فتح الشاشة"]},
  hard:{en:"Thousands of listings on one map choke the screen. Clustering plus progressive loading kept it smooth.",
        ar:"آلاف الإعلانات على خريطة واحدة تثقل الشاشة. تجميع النقاط والتحميل التدريجي حافظ على السلاسة."},
  tech:["Flutter","BLoC","Clean Architecture","Google Maps","Firebase"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.aqarmap.android"},{t:"ios",u:"https://apps.apple.com/app/id642633889"}],
  icon:"https://play-lh.googleusercontent.com/SMTnakgVfrHXtNZoeKzYELeohMgdUdTu6OcyRkgcJiAG_9JbHhLgXVBXyUxUL38E32D7NmsjiOZ9nj_PpcJdqA=w240",
  shots:["https://play-lh.googleusercontent.com/cRjxwUBdHc8o6NEFAf9cpmsVPQ8pVeYzx0sdyxpZNK2ghbB_frMJOsHC9q2E6oYJJzM6JIiSubko1fu7xcIv=w1000",
"https://play-lh.googleusercontent.com/gqsZm7xOuwgN8V6Gvh3H-OB7JJVaCh8elnpmb32a0zUeZEiSIVcjixJzgLcuBDmqDv_rJBmTELQIpeXo90ag7Q=w1000",
"https://play-lh.googleusercontent.com/xjWjOQ5rcdmxFkpMs7pllcLAHf3EdwegO_Se99fRlGPk0KGNok4lVTcB9U3zLCBVt3SE6Qg3ZzJ-FyEPncugpw=w1000",
"https://play-lh.googleusercontent.com/TqUZMzqXU_VAqKDTGqetAL0VjeEDJuMptxPFbiYqY3PoSVUGG024QNv_kR7KrjY8bC79A6v6Hd61MGYbRqOHsw=w1000",
"https://play-lh.googleusercontent.com/rBBDaIxWH3G2FlPHJweO24GZ4zWqiewBH53pP75S6jVhdLUuTaTXKAyGkqjwwEr7IMfQlN1w8rrEEi96M8ctG8o=w1000",
"https://play-lh.googleusercontent.com/eEHCFLU1UEUoB3T1e236Vs2iWI59kYg0RZ3h-Tn0titcEq9GePJpJMzQm0ui6lHgqfKEngQDTKAZ2qX7d623Kg=w1000"] },

{ key:"aqarmap-ksa", year:"2024", flag:"🇸🇦",
  name:{en:"Aqarmap KSA", ar:"عقارماب السعودية"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Property marketplace for home buyers in Saudi Arabia", ar:"منصة عقارات لمشتري البيوت في السعودية"},
  tags:{en:["Real estate","Local rules","Government link"], ar:["عقارات","قوانين محلية","ربط حكومي"]},
  stats:[{v:"AR / EN", l:{en:"both languages",ar:"واجهة باللغتين"}},{v:{en:"Hijri",ar:"هجري"}, l:{en:"contract calendar",ar:"تقويم العقود"}}],
  body:{en:"Saudi home buyers search listings and work out the return in riyals. Official rental contracts go through the government Ejar platform.",
        ar:"المشتري السعودي يتصفح الإعلانات ويحسب عائد الاستثمار بالريال. منصة إيجار الحكومية توثق كل عقد إيجار رسمي."},
  built:{en:["Hijri calendar for contract dates","Investment return calculator with currency conversion","A link to Ejar for official contracts","Arabic and English interface, right to left"],
         ar:["تقويم هجري لتواريخ العقود","حاسبة عائد استثمار مع تحويل العملات","ربط بمنصة إيجار للعقود الرسمية","واجهة بالعربية والإنجليزية من اليمين لليسار"]},
  hard:{en:"One codebase had to serve two very different markets. Splitting the shared code from the local rules made it work.",
        ar:"قاعدة كود واحدة تخدم سوقين بقوانين مختلفة. الفصل بين المشترك والمحلي هو ما جعلها تعمل."},
  tech:["Flutter","BLoC","l10n","RTL","REST"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.aqarmap.invest"},{t:"ios",u:"https://apps.apple.com/app/id6470154017"}],
  icon:"https://play-lh.googleusercontent.com/Xbn_5Bzk_t7b2FoTJdMZZQhlXB7ZbaOtZACveCAgiefuqJRruydJxHvmB5JoyVS5BNKxdl_miTIGkQdO-rhsXzk=w240",
  shots:["https://play-lh.googleusercontent.com/jEFpN0vhU0_js0KV8sYCLtHDGxcEj1LA1kl-cCQ352AHeQDuPDmLhH_YHHyXAaslTOcL2ZhhhT4nb3PmeiERhw=w1000",
"https://play-lh.googleusercontent.com/rI36zphU7P2aPuwyG5HGJTN87wCECzHOPf1Ol_Ba15nVNxeM3TIyll2eWrcFahd_VryhXZHGh08FLh-PTkBj5aw=w1000",
"https://play-lh.googleusercontent.com/0fXocQ9QJNeMx6Wxq2ayDUrOFPaUgDinNjqeUx2Esqve1ln_1RY9umI-BRUHacR_Y13xQn7HpH0EXFADLaLjzPI=w1000",
"https://play-lh.googleusercontent.com/77V3pWLA1fxM73qOv4a8g8SPvkqEpeOvtdtqFA1WXfDr-C480IMiNM2Pk46KZgGsfB_yLt_LzE69W6eZGuFzi8Y=w1000",
"https://play-lh.googleusercontent.com/CxgCXmveElRCcfoN2sSRFge7Xvzh7oqrf8jrT2Me0sF5E-ijiMcP2qV1ouEQCBQjlMTBiZ5CX68I6Bgwhku1tA=w1000",
"https://play-lh.googleusercontent.com/rHH3abwafoheSKNMg90fH44Z3b5XtN3UGgwiIkmusC0yghN7d9zFuFbdBeirRg-OBv4n-gC-Ie_JMPbUIq5Gy3Q=w1000"] },

{ key:"aqarmap-crm", year:"2024", flag:"🏢",
  name:{en:"Aqarmap CRM", ar:"عقارماب CRM"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Sales tracker for property agents in the field", ar:"متابعة مبيعات لمندوبي العقارات في الميدان"},
  tags:{en:["Sales pipeline","Works with no signal","Syncing"], ar:["مسار مبيعات","يعمل بلا شبكة","مزامنة"]},
  stats:[{v:"100K+", l:{en:"leads a month",ar:"عميل محتمل شهرياً"}},{v:"4.4★", l:{en:"store rating",ar:"تقييم المتجر"}},{v:"5", l:{en:"pipeline stages",ar:"مراحل المبيعات"}}],
  body:{en:"Agents log leads while standing in basements and half-finished buildings with no signal. The app carries more than 100,000 leads a month.",
        ar:"المندوب يسجل عملاءه وهو في بدرومات ومباني لم تكتمل بلا تغطية. النظام يحمل أكثر من ١٠٠ ألف عميل محتمل شهرياً."},
  built:{en:["A five-stage sales pipeline","A local database that works with no signal","A queue that uploads once coverage returns","Live notifications, calendar sync and automatic follow-ups","An analytics dashboard with conversion rates"],
         ar:["مسار مبيعات من ٥ مراحل","قاعدة بيانات محلية تعمل بلا شبكة","طابور رفع يعمل فور عودة التغطية","إشعارات لحظية ومزامنة تقويم ومتابعات تلقائية","لوحة تحليلات بمعدلات التحويل"]},
  hard:{en:"Two phones can edit the same lead with no signal. A fixed rule settles the conflict, not the last write.",
        ar:"جهازان يعدّلان العميل نفسه بلا شبكة. قاعدة ثابتة تحسم التعارض، لا آخر كتابة."},
  tech:["Flutter","SQLite","Offline-first","Firebase Messaging","Background Services"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.project.aqarmap.crm"},{t:"ios",u:"https://apps.apple.com/app/id1271197604"}],
  icon:"https://play-lh.googleusercontent.com/yELBszBts6idqTepQho3gjHGW0PbotZlybNr0Uf7v9dn-P7CDycypK4-4yl76ly1X5yGYNfrU6GphreVLYB0=w240",
  shots:["https://play-lh.googleusercontent.com/1NSYRhxDm1Cqhe9V7D8akGARmARAzFx0ziSHClXaCTHOgISPKD-f_WPmrZd_-NqdK7Axo15Ui8EW0QKSjUhEAQ=w1000",
"https://play-lh.googleusercontent.com/uuMKiRCPh4dev-nUef-0CFs2SPhYAvoN0stsZUorq8IUwrhwtMlLxYL_CucgMEAt8Yr1OskW-T46WjoMXilf4Io=w1000",
"https://play-lh.googleusercontent.com/qX8UVvyGjX_acjgysMgqwZXrfEmm_0ATS4Ps_K9-UvoEq6J-QFWTAHLQPodSLU9DT7qH5xyVegdwhQTPvm6T=w1000",
"https://play-lh.googleusercontent.com/lmTsmOqs8nqlpWTzMCsB6HI9M0BNntuUmSh5UueHkjXEynaxPsWf-6ATdHEJrz2dUkdCvSnNIezYFcMpYgaJsA=w1000"] },

{ key:"adam", year:"2022", flag:"🇸🇦",
  name:{en:"Adam Pharmacy", ar:"صيدلية آدم"},
  role:{en:"Flutter Developer and Team Lead", ar:"مطور Flutter وقائد الفريق"},
  one:{en:"Online pharmacy for customers with a prescription", ar:"صيدلية إلكترونية لأصحاب الوصفات الطبية"},
  tags:{en:["Healthcare","Delivery","Prescription reading"], ar:["صحة","توصيل","قراءة الوصفة"]},
  stats:[{v:"10K+", l:{en:"downloads",ar:"تحميل"}},{v:"4.6★", l:{en:"store rating",ar:"تقييم المتجر"}},{v:"3", l:{en:"developers on the team",ar:"مطورين في الفريق"}}],
  body:{en:"Customers photograph a handwritten prescription instead of typing every medicine. A pharmacist checks every order before it leaves.",
        ar:"العميل يصوّر الوصفة المكتوبة بخط اليد بدل كتابة كل دواء. صيدلي يراجع كل طلب قبل خروجه."},
  built:{en:["Prescription reading through the phone camera","Live order tracking to the door","Reminders for every medication time","Card payment and push notifications"],
         ar:["قراءة الوصفة بكاميرا الجوال","تتبع الطلب لحظياً حتى الباب","تذكير بكل موعد دواء","دفع بالبطاقة وإشعارات فورية"]},
  hard:{en:"A wrong medicine is not a bug you fix later. Images get cleaned before reading, and a pharmacist confirms every order.",
        ar:"الدواء الخطأ لا تقدر تصلحه بعد ما يخرج. التطبيق ينقي الصورة قبل القراءة، والصيدلي يؤكد الطلب."},
  tech:["Flutter","Firebase","OCR","Payment Gateway","Google Maps"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.adampharmacy"},{t:"ios",u:"https://apps.apple.com/app/id1672276218"}],
  icon:"https://play-lh.googleusercontent.com/r01GfpnAxEShNXIHee2gibLe-fMM56JBBQZhzcX22T0yQ1LQlA8w5EwNBZPtexzbpYI_mYVhLw0aGEODXRtB=w240",
  shots:["https://play-lh.googleusercontent.com/ZgpsLb3krfungshYUz_GoVqVu3RJ3OOKZQXGW-7cbjoDzRoU006S7Vwxqzuhg08Hp-jQTlFmL7YFNfANgonG=w1000",
"https://play-lh.googleusercontent.com/xGyl16_IxFC82fvxtE2RrcZF9916Zd-ZnuDobj6-Q6TPGBIRc5tdefzePtPXXFzaTvrcXdCmY-Q1ezjnNx5-iQ=w1000",
"https://play-lh.googleusercontent.com/OjEywH7XhKWhkLcKeiD0jzzDUPS33YnhspWsEeDZRFMXlmNqU6hnv6-UOgGOoc0WRjGSNskqf4MMPeHTNrYer0c=w1000",
"https://play-lh.googleusercontent.com/LiUQSIRyRxcB-YF39YJShyq7Qt6YpvH_geO9W0nSfvVCpT115NTr6amxQDDSoCHb-V1anTfTF-c_c3Tpu7awPGA=w1000",
"https://play-lh.googleusercontent.com/kL6JNt2LxRpK-cpE55jWVPaFzQmQTx3VXEGvpcTTTiWNl6o2HW8fRud7-1Y9-9jt1pq5rxczQGDbUHEsoPWY=w1000"] },

{ key:"bizbura", year:"2022", flag:"🇹🇷",
  name:{en:"BizBuradayız", ar:"بيز بورادايز"},
  role:{en:"Flutter Developer", ar:"مطور Flutter"},
  one:{en:"Roadside help for drivers stuck in Turkey", ar:"مساعدة على الطريق لسائقي السيارات في تركيا"},
  tags:{en:["Roadside help","Live tracking","Two apps"], ar:["مساعدة على الطريق","تتبع لحظي","تطبيقان"]},
  stats:[{v:"2", l:{en:"apps, one system",ar:"تطبيق في نظام واحد"}},{v:{en:"Live",ar:"لحظي"}, l:{en:"map tracking",ar:"تتبع على الخريطة"}}],
  body:{en:"A stranded driver requests help and follows the provider on the map. The customer app and the provider app share one system.",
        ar:"السائق المتعطل يطلب المساعدة ويتابع المزوّد على الخريطة. تطبيق العميل وتطبيق المزوّد يعملان على نظام واحد."},
  built:{en:["One system behind two apps","Instant matching to the nearest provider","Live location on the map","In-app chat with order updates","Photo reviews after the job"],
         ar:["نظام واحد خلف تطبيقين","مطابقة فورية مع أقرب مزوّد خدمة","موقع لحظي على الخريطة","محادثة داخل التطبيق مع تحديثات الطلب","تقييمات بالصور بعد انتهاء الخدمة"]},
  hard:{en:"A late screen leaves someone standing on the hard shoulder. Pusher and one state layer keep both apps in step.",
        ar:"الشاشة المتأخرة تترك شخصاً واقفاً على جانب الطريق. طبقة حالة واحدة مع Pusher تحافظ على تطابق التطبيقين."},
  tech:["Flutter","BLoC","Pusher","Google Maps","Real-time Tracking"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.bizburadayiz",label:{en:"Customer app",ar:"تطبيق العميل"}},
         {t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.bizburadayiz.driver",label:{en:"Provider app",ar:"تطبيق مزود الخدمة"}}],
  icon:"https://play-lh.googleusercontent.com/V6df11qDA0Y-Wo1eY4KAbzd5QnGtC13OmHLRKN2sI-VMdWt_jG9v3gPVlljxFjsnMlyxbhI87FflayM76pnpcIM=w240",
  shots:["https://play-lh.googleusercontent.com/Q3BaS6DWURTUvmD8ikJKsHZnaQo6JBhEi2-7CVBqwjiSnWy6BxHyrI40Gg09T96CQNh3xqXJ2mFs6HsfkeWECw=w1000",
"https://play-lh.googleusercontent.com/QEwCQQwvwmeEjhqUBDrjWseSqrucIFbwvF1tRAN34PUgHiiUSf2NF_dYlmvn7khEgy_1MrQP-K_XIu5VeMQNCg=w1000",
"https://play-lh.googleusercontent.com/9mepB9E6CuC0OEQE5cpC6UXF5c-PzD4rHhSjGdZz95u4G61D6llqCGopZbCvPfcdHt6W42UkADza3G0ziD6v=w1000",
"https://play-lh.googleusercontent.com/DjzSxxpDKar6qLgWpg3enxPPQxI6GFO_sAc2FqyLBVE-4NvuLyp2qMLOMX5ijkUwfHGQlosGz3NL58MPQrJ35w=w1000",
"https://play-lh.googleusercontent.com/Xc4G7CXdwhV3XnGWjWRCaGgfZPtVhhkik86kdLMSihU6-xceHQUgwQ9MapYaToiBEzG9c6lX1B664YHNSNUJbQ=w1000",
"https://play-lh.googleusercontent.com/gcRVkt-yqmrU8E9uU-DonU8gE6QLus3IypAbHf3lTGxwVRoKqaNro0F2DnCldAWc18fKKPMYdUO2bu8cTDbsrw=w1000"] },

{ key:"alnasser", year:"2022", flag:"🇰🇼",
  name:{en:"ALNASSER", ar:"الناصر"},
  role:{en:"Flutter Developer", ar:"مطور Flutter"},
  one:{en:"Fashion and sports store for shoppers in Kuwait", ar:"متجر أزياء ورياضة لمتسوقي الكويت"},
  tags:{en:["Shopping","Loyalty points","Campaign links"], ar:["تسوق","نقاط ولاء","روابط الحملات"]},
  stats:[{v:"100K+", l:{en:"downloads",ar:"تحميل"}},{v:"50+", l:{en:"stores in Kuwait",ar:"فرع في الكويت"}},{v:"8", l:{en:"countries",ar:"دول"}}],
  body:{en:"Shoppers buy clothes and sportswear from a chain they already know. The chain runs more than 50 stores in Kuwait and seven other countries.",
        ar:"المتسوق يشتري الملابس والمستلزمات الرياضية من سلسلة يعرفها. للسلسلة أكثر من ٥٠ فرعاً في الكويت وحضور في ٧ دول أخرى."},
  built:{en:["A catalogue with filters and a size guide","Loyalty points and member-only discounts","Several payment methods at checkout","Campaign links that open the exact product"],
         ar:["كتالوج بفلترة متقدمة ودليل مقاسات","نقاط ولاء وخصومات للأعضاء","طرق دفع متعددة عند الشراء","روابط حملات تفتح المنتج نفسه"]},
  hard:{en:"A campaign click has to land on that exact product. It works whether the app is installed or not.",
        ar:"النقرة على إعلان الحملة يجب أن تفتح المنتج نفسه. تعمل سواء كان التطبيق مثبتاً أو غير مثبت."},
  tech:["Flutter","Provider","Deep Linking","Payment","Firebase Analytics"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.alnasser"}],
  icon:"https://play-lh.googleusercontent.com/UAh109EbkFdE4tJNM_oWhxwsRnX1TbdIxScZkWML5dTWEzSBRfkAnqetrr6uvR_i61pdIkrvLB9PwNs1bhV3wA=w240",
  shots:["https://play-lh.googleusercontent.com/67vbk5ytrzBWgFD_8Y4SEeGWeTo5jhDeK5HA9mVAwMFInmP9OE5Ur5cyUQkufikULSD62TY8oWXsMEx5A-bNjg=w1000",
"https://play-lh.googleusercontent.com/MJKb7bgO9eMAU-Ez_EB2ah7w5BSrgpdH9Phfrlu_wMwXz8naHhPxIWx7j_Au1nuiX-gGP2lcKDEuBltKygh6sA=w1000",
"https://play-lh.googleusercontent.com/7-uDohTXv5SZYApY3muJ5qNELez3wT4V2ck-DIP9zGlk4zdZ1OntfG24q3P5OYONt7be_Q1TOoFGNl-juBIszg=w1000",
"https://play-lh.googleusercontent.com/PQ0K-l75JtTZbd6YK0LPnBKUari3J9nNyzMBsy1qkAXFanRS_JACINgRWKSo6pH8AxazZGLcRb7yvY5l7igD=w1000",
"https://play-lh.googleusercontent.com/vVea8RTvThhk3us3cK3jwr7MXpgB0Mba5K0GqLpwA5ogeHmzjOpRwsUKqwOVLNcdyeZ451REiG1YICfqZcuq7jA=w1000"] },

{ key:"hr-portal", year:"2024", flag:"🇸🇦",
  name:{en:"TBS Self-Services", ar:"خدمة ذاتية للموظفين"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Self-service app for employees and their managers", ar:"تطبيق خدمة ذاتية للموظفين ومديريهم"},
  tags:{en:["Human resources","Fingerprint sign-in","Saudi payroll"], ar:["موارد بشرية","دخول بالبصمة","رواتب سعودية"]},
  stats:[{v:"17", l:{en:"request forms",ar:"نموذج طلب"}},{v:{en:"Live codebase",ar:"كود قائم"}, l:{en:"joined 2024",ar:"انضممت 2024"}}],
  body:{en:"Employees file their own requests instead of walking to the HR office. Managers approve from the same app.",
        ar:"الموظف يقدّم طلباته بنفسه بدل الذهاب إلى إدارة الموارد البشرية. والمدير يوافق من التطبيق نفسه."},
  built:{en:["Leave, loan and expense request forms","Clock in and out by location","Sign-in by face or fingerprint","Payslips and contracts to download"],
         ar:["نماذج طلبات الإجازة والسلفة والمصروفات","حضور وانصراف بالموقع الجغرافي","دخول ببصمة الوجه أو الإصبع","قسائم الراتب والعقود للتحميل"]},
  hard:{en:"One form holds an Arabic field and an English field. Two separate validators, plus Saudi IBAN and phone checks.",
        ar:"الفورم الواحد فيه حقل عربي وحقل إنجليزي. تحقّقان منفصلان, ومعهما تحقق الآيبان ورقم الجوال السعودي."},
  tech:["Flutter","BLoC","Odoo","Biometric Auth","Geolocation","Localization"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=sa.com.takamoltbs.selfservices"},{t:"ios",u:"https://apps.apple.com/sa/app/id6447533663"}],
  icon:"https://is1-ssl.mzstatic.com/image/thumb/Purple221/v4/82/1f/a7/821fa7a9-0fad-53c3-75d1-7e8eedffe73c/AppIcon-0-0-1x_U007emarketing-0-7-0-0-85-220.png/512x512bb.jpg",
  shots:["https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/f2/71/3d/f2713d59-4e70-ad7b-fb3d-32dd2d4e0cac/c1d67390-a6c3-4b98-beb7-ca912148f591_Apple_iPhone_8_Plus_Screenshot_1.png/392x696bb.png",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/09/39/f3/0939f3df-e53b-97ff-3f40-afab904e67b9/7996b429-3584-487f-ae2c-43818a7fc30b_Apple_iPhone_8_Plus_Screenshot_2.png/392x696bb.png",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/2d/d1/03/2dd103b9-08f9-2742-649c-92b1bb09de24/5ddd6658-66c3-4a2c-b62f-8b064aa204ed_Apple_iPhone_8_Plus_Screenshot_3.png/392x696bb.png"] },

{ key:"pm-tablet", year:"2024", flag:"🇸🇦",
  name:{en:"TBS EPM", ar:"إدارة محفظة المشاريع"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Portfolio dashboards and reports for programme managers", ar:"لوحات وتقارير لمديري محفظة المشاريع"},
  tags:{en:["Project reporting","Dashboards","Tablet"], ar:["تقارير المشاريع","لوحات","لوحي"]},
  stats:[{v:"16", l:{en:"report modules",ar:"وحدة تقارير"}},{v:{en:"Landscape",ar:"أفقي"}, l:{en:"tablet only",ar:"لوحي فقط"}}],
  body:{en:"Programme managers read where a portfolio stands: what is late, what is at risk, and what the budget says.",
        ar:"مدير البرنامج يقرأ وضع المحفظة: ما تأخّر, وما يتعرّض للخطر, وما تقوله الميزانية."},
  built:{en:["Dashboards for portfolio, programme and project","Status, risk, issue and deliverable reports","Schedules, budgets and invoicing","Progressive loading for long reports"],
         ar:["لوحات للمحفظة والبرنامج والمشروع","تقارير الحالة والمخاطر والقضايا والمخرجات","الجداول الزمنية والميزانيات والفوترة","تحميل تدريجي للتقارير الطويلة"]},
  hard:{en:"Reports arrive one page at a time, and search has to work on what already loaded. Local search merged with paging.",
        ar:"التقرير يصل صفحة صفحة, والبحث يجب أن يعمل على ما وصل بالفعل. دمجنا البحث المحلي مع الترحيل."},
  tech:["Flutter","BLoC","fl_chart","Syncfusion","Pagination","Tablet UI"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=sa.com.takamoltbs.epm"},{t:"ios",u:"https://apps.apple.com/sa/app/id6450037705"}],
  icon:"https://is1-ssl.mzstatic.com/image/thumb/Purple126/v4/33/42/18/33421854-7ad8-9adb-546e-bd5e3188b685/AppIcon-0-0-1x_U007emarketing-0-0-0-7-0-0-sRGB-0-0-0-GLES2_U002c0-512MB-85-220-0-0.png/512x512bb.jpg",
  shots:["https://is1-ssl.mzstatic.com/image/thumb/PurpleSource116/v4/5c/fe/6a/5cfe6ad1-72f5-2328-c333-9ea3bfa0720f/53a3524d-da90-4688-829f-359665922877_Apple_iPhone_8_Plus_Screenshot_0.png/392x696bb.png",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/c9/e9/8d/c9e98d3b-867c-46f8-2e8e-fcda3d0b4d4e/7fb1b791-09f8-4925-86c5-f1d6165ec942_Apple_iPhone_8_Plus_Screenshot_1.png/392x696bb.png",
"https://is1-ssl.mzstatic.com/image/thumb/PurpleSource126/v4/c0/e1/7b/c0e17be5-3781-222d-20c9-025957571c64/d1e55adc-9787-40e3-bd47-ce06c9121b87_Apple_iPhone_8_Plus_Screenshot_2.png/392x696bb.png"] },

{ key:"yseer", year:"2025", flag:"🇸🇦",
  name:{en:"Yseer", ar:"يسير"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Ordering and delivery app for customers in Riyadh", ar:"تطبيق طلب وتوصيل لسكان الرياض"},
  tags:{en:["Delivery","Live updates","Payments"], ar:["توصيل","تحديثات لحظية","مدفوعات"]},
  stats:[{v:{en:"Riyadh",ar:"الرياض"}, l:{en:"operating city",ar:"مدينة التشغيل"}},{v:{en:"Events",ar:"الأحداث"}, l:{en:"ordered, not raced",ar:"مرتبة لا متسابقة"}}],
  body:{en:"Customers order goods and follow the delivery until it reaches the door. The platform operates across the city of Riyadh.",
        ar:"العميل يطلب ويتابع التوصيل حتى وصوله إلى الباب. المنصة تعمل في مدينة الرياض."},
  built:{en:["A returns and refunds module","Live order events over WebSocket and Pusher","An ordered log of every state change","A rebuild of the booking and order journeys"],
         ar:["وحدة المرتجعات والمعاملات المالية","أحداث لحظية للطلب عبر WebSocket و Pusher","سجل مرتب لكل تغيير في الحالة","إعادة بناء مسارات الحجز والطلبات"]},
  hard:{en:"Several sources write the same order state at once. Ordering the events stopped them colliding.",
        ar:"أكثر من مصدر يكتب حالة الطلب في اللحظة نفسها. ترتيب الأحداث أنهى التعارض."},
  tech:["Flutter","BLoC","REST","WebSocket / Pusher"],
  links:[], internal:true,
  icon:"", shots:[] }
];

/* Text specific to the apps page. Everything shared (name, profiles, bar,
   footer) lives in /assets/shell.js — do not restate any of it here. */
window.PAGE = {
  title:{en:"Ahmed ElFirgany — App Catalogue", ar:"أحمد الفرجاني — كتالوج التطبيقات"},
  tagline:{en:"Apps that shipped, and are still running.", ar:"تطبيقات نزلت فعلا، وما زالت تعمل."},
  intro:{en:"18+ apps across five countries, with 600K+ downloads on Google Play alone. Each card below carries the hard part and a link that opens.",
         ar:"أكثر من ١٥ تطبيقاً في ٥ دول، وأكثر من ٦٠٠ ألف تحميل على Google Play. مع كل تطبيق هنا أصعب جزء فيه ورابط يفتح الآن."},
  stats:[{v:"18+", l:{en:"apps",ar:"تطبيق"}},{v:"600K+", l:{en:"downloads",ar:"تحميل"}},
         {v:"5", l:{en:"countries",ar:"دول"}},{v:"5+", l:{en:"years",ar:"سنوات خبرة"}}],
  fine:{en:"Screenshots come from the public store listings.", ar:"اللقطات من صفحات المتاجر العامة."},
  cross:{
    eyebrow:{en:"The other half", ar:"النصف الآخر"},
    h:{en:"The games", ar:"الألعاب"},
    p:{en:"The games are where we push Flutter further. Real 3D on the graphics card, real Box2D physics. Both play in your browser.",
       ar:"الألعاب مساحة ندفع فيها Flutter إلى أبعد. رسوم ثلاثية الأبعاد على بطاقة الرسوميات، وفيزياء Box2D حقيقية. كلتاهما تعمل في متصفحك الآن."},
    btn:{en:"Open the games", ar:"افتح الألعاب"},
    to:"games"
  }
};
