// The only data file for the catalogue. Adding an app = a block here. No HTML edits.
window.APPS = [
{ key:"aqarmap-eg", year:"2024", flag:"🇪🇬",
  name:{en:"Aqarmap Egypt", ar:"عقارماب مصر"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Egypt's largest real-estate marketplace", ar:"أكبر منصة عقارات في مصر"},
  tags:{en:["Real estate","Maps","Search & filters"], ar:["عقارات","خرائط","بحث وفلاتر"]},
  stats:[{v:"500K+", l:{en:"downloads",ar:"تحميل"}},{v:"4.6★", l:{en:"from 6.1K ratings",ar:"من ٦١٠٠ تقييم"}},{v:"200K+", l:{en:"listings",ar:"عقار معروض"}},{v:"~30%", l:{en:"faster loads",ar:"أسرع بعد التحسين"}}],
  body:{en:"About two million visitors a month and over 200,000 live listings. All of it on one map. I built the search engine, the clustering layer and the performance pass.",
        ar:"نحو مليوني زائر شهرياً، وأكثر من ٢٠٠ ألف إعلان نشط. كلها معروضة على خريطة واحدة. بنيتُ محرك البحث، وطبقة تجميع النقاط والخرائط الحرارية، وخطة تحسين الأداء."},
  built:{en:["Search engine with 15+ dynamic filters","Interactive map with clustering and heat maps","Neighbourhood analytics on the map","Performance pass that cut screen-open time"],
         ar:["محرك بحث بأكثر من ١٥ فلتراً متغيراً","خريطة تفاعلية بتجميع نقاط وخرائط حرارية","تحليلات للأحياء على الخريطة","تحسين الأداء وتقليل زمن فتح الشاشات"]},
  hard:{en:"Thousands of listings on one map. Clustering plus progressive loading kept it smooth.",
        ar:"آلاف الإعلانات على خريطة واحدة. الحل كان تجميع النقاط والتحميل التدريجي."},
  tech:["Flutter","BLoC","Clean Architecture","Google Maps","Firebase"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.aqarmap.android"},{t:"ios",u:"https://apps.apple.com/app/id642633889"}],
  icon:"https://play-lh.googleusercontent.com/SMTnakgVfrHXtNZoeKzYELeohMgdUdTu6OcyRkgcJiAG_9JbHhLgXVBXyUxUL38E32D7NmsjiOZ9nj_PpcJdqA=w240",
  shots:["https://play-lh.googleusercontent.com/cRjxwUBdHc8o6NEFAf9cpmsVPQ8pVeYzx0sdyxpZNK2ghbB_frMJOsHC9q2E6oYJJzM6JIiSubko1fu7xcIv=w1000",
"https://play-lh.googleusercontent.com/gqsZm7xOuwgN8V6Gvh3H-OB7JJVaCh8elnpmb32a0zUeZEiSIVcjixJzgLcuBDmqDv_rJBmTELQIpeXo90ag7Q=w1000",
"https://play-lh.googleusercontent.com/xjWjOQ5rcdmxFkpMs7pllcLAHf3EdwegO_Se99fRlGPk0KGNok4lVTcB9U3zLCBVt3SE6Qg3ZzJ-FyEPncugpw=w1000",
"https://play-lh.googleusercontent.com/TqUZMzqXU_VAqKDTGqetAL0VjeEDJuMptxPFbiYqY3PoSVUGG024QNv_kR7KrjY8bC79A6v6Hd61MGYbRqOHsw=w1000",
"https://play-lh.googleusercontent.com/rBBDaIxWH3G2FlPHJweO24GZ4zWqiewBH53pP75S6jVhdLUuTaTXKAyGkqjwwEr7IMfQlN1w8rrEEi96M8ctG8o=w1000",
"https://play-lh.googleusercontent.com/eEHCFLU1UEUoB3T1e236Vs2iWI59kYg0RZ3h-Tn0titcEq9GePJpJMzQm0ui6lHgqfKEngQDTKAZ2qX7d623Kg=w1000"] },

{ key:"aqarmap-ksa", year:"2024", flag:"🇸🇦",
  name:{en:"Aqarmap KSA", ar:"عقارماب السعودية"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"The Saudi build, localised end to end", ar:"نسخة السوق السعودي، موطّنة بالكامل"},
  tags:{en:["Real estate","Localisation","Government integration"], ar:["عقارات","توطين","ربط حكومي"]},
  stats:[{v:"AR / EN", l:{en:"full bilingual",ar:"دعم كامل للغتين"}},{v:{en:"Hijri",ar:"هجري"}, l:{en:"contract calendar",ar:"تقويم العقود"}}],
  body:{en:"Same codebase as the Egyptian app, different country rules. Hijri contract dates and riyal calculations. Every official rental contract goes through Ejar, so the app connects to it.",
        ar:"قاعدة كود واحدة مع التطبيق المصري، وقواعد دولة مختلفة. تواريخ عقود هجرية، وحاسبة عائد بالريال. كل عقد إيجار رسمي يمر عبر منصة إيجار، فربطتُ التطبيق بها."},
  built:{en:["Hijri calendar for contract dates","Investment ROI calculator with currency conversion","Ejar integration for official Saudi rental contracts","Bilingual Arabic and English UI, full RTL"],
         ar:["تقويم هجري لتواريخ العقود","حاسبة عائد استثمار وتحويل عملات","ربط بمنصة إيجار للعقود الرسمية","واجهة عربية وإنجليزية، ودعم كامل للكتابة من اليمين لليسار"]},
  hard:{en:"One codebase, two markets. Separating the shared code from the local rules made it work.",
        ar:"قاعدة كود واحدة لسوقين مختلفين. الفصل بين المشترك والمحلي هو ما جعلها تعمل."},
  tech:["Flutter","BLoC","l10n","RTL","REST"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.aqarmap.invest"},{t:"ios",u:"https://apps.apple.com/app/id6470154017"}],
  icon:"https://play-lh.googleusercontent.com/Xbn_5Bzk_t7b2FoTJdMZZQhlXB7ZbaOtZACveCAgiefuqJRruydJxHvmB5JoyVS5BNKxdl_miTIGkQdO-rhsXzk=w240",
  shots:["https://play-lh.googleusercontent.com/jEFpN0vhU0_js0KV8sYCLtHDGxcEj1LA1kl-cCQ352AHeQDuPDmLhH_YHHyXAaslTOcL2ZhhhT4nb3PmeiERhw=w1000",
"https://play-lh.googleusercontent.com/rI36zphU7P2aPuwyG5HGJTN87wCECzHOPf1Ol_Ba15nVNxeM3TIyll2eWrcFahd_VryhXZHGh08FLh-PTkBj5aw=w1000",
"https://play-lh.googleusercontent.com/0fXocQ9QJNeMx6Wxq2ayDUrOFPaUgDinNjqeUx2Esqve1ln_1RY9umI-BRUHacR_Y13xQn7HpH0EXFADLaLjzPI=w1000",
"https://play-lh.googleusercontent.com/77V3pWLA1fxM73qOv4a8g8SPvkqEpeOvtdtqFA1WXfDr-C480IMiNM2Pk46KZgGsfB_yLt_LzE69W6eZGuFzi8Y=w1000",
"https://play-lh.googleusercontent.com/CxgCXmveElRCcfoN2sSRFge7Xvzh7oqrf8jrT2Me0sF5E-ijiMcP2qV1ouEQCBQjlMTBiZ5CX68I6Bgwhku1tA=w1000",
"https://play-lh.googleusercontent.com/rHH3abwafoheSKNMg90fH44Z3b5XtN3UGgwiIkmusC0yghN7d9zFuFbdBeirRg-OBv4n-gC-Ie_JMPbUIq5Gy3Q=w1000"] },

{ key:"aqarmap-crm", year:"2024", flag:"🏢",
  name:{en:"Aqarmap CRM", ar:"عقارماب CRM"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Offline-first CRM for real-estate companies", ar:"نظام إدارة عملاء عقاري يعمل دون اتصال"},
  tags:{en:["CRM","Offline-first","Sync"], ar:["CRM","عمل دون اتصال","مزامنة"]},
  stats:[{v:"100K+", l:{en:"leads a month",ar:"عميل محتمل شهرياً"}},{v:"4.4★", l:{en:"store rating",ar:"تقييم المتجر"}},{v:"5", l:{en:"pipeline stages",ar:"مراحل المبيعات"}}],
  body:{en:"Agents work in basements and half-built compounds with no signal. The app writes to a local database and syncs when coverage returns. It carries over 100,000 leads a month.",
        ar:"المندوب يعمل في أقبية ومجمعات قيد الإنشاء بلا تغطية. التطبيق يكتب في قاعدة بيانات محلية، ويزامن فور عودة الشبكة. يحمل أكثر من ١٠٠ ألف عميل محتمل شهرياً."},
  built:{en:["Five-stage sales pipeline","Offline-first architecture with a sync queue","No edit lost when coverage drops","Live notifications, calendar sync, automatic follow-ups","Analytics dashboard with conversion rates"],
         ar:["مسار مبيعات من ٥ مراحل","معمارية تعمل دون اتصال مع طابور مزامنة","لا يضيع أي تعديل عند انقطاع الشبكة","إشعارات لحظية، ومزامنة تقويم، ومتابعات تلقائية","لوحة تحليلات بمعدلات التحويل"]},
  hard:{en:"Conflicts. Two devices editing the same lead offline resolve by a fixed rule, not last-write-wins.",
        ar:"التعارض. جهازان يعدّلان العميل نفسه دون اتصال. الحسم يكون بقاعدة ثابتة، لا بآخر كتابة."},
  tech:["Flutter","SQLite","Offline-first","Firebase Messaging","Background Services"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.project.aqarmap.crm"},{t:"ios",u:"https://apps.apple.com/app/id1271197604"}],
  icon:"https://play-lh.googleusercontent.com/yELBszBts6idqTepQho3gjHGW0PbotZlybNr0Uf7v9dn-P7CDycypK4-4yl76ly1X5yGYNfrU6GphreVLYB0=w240",
  shots:["https://play-lh.googleusercontent.com/1NSYRhxDm1Cqhe9V7D8akGARmARAzFx0ziSHClXaCTHOgISPKD-f_WPmrZd_-NqdK7Axo15Ui8EW0QKSjUhEAQ=w1000",
"https://play-lh.googleusercontent.com/uuMKiRCPh4dev-nUef-0CFs2SPhYAvoN0stsZUorq8IUwrhwtMlLxYL_CucgMEAt8Yr1OskW-T46WjoMXilf4Io=w1000",
"https://play-lh.googleusercontent.com/qX8UVvyGjX_acjgysMgqwZXrfEmm_0ATS4Ps_K9-UvoEq6J-QFWTAHLQPodSLU9DT7qH5xyVegdwhQTPvm6T=w1000",
"https://play-lh.googleusercontent.com/lmTsmOqs8nqlpWTzMCsB6HI9M0BNntuUmSh5UueHkjXEynaxPsWf-6ATdHEJrz2dUkdCvSnNIezYFcMpYgaJsA=w1000"] },

{ key:"adam", year:"2022", flag:"🇸🇦",
  name:{en:"Adam Pharmacy", ar:"صيدلية آدم"},
  role:{en:"Flutter Developer & Team Lead", ar:"مطور Flutter وقائد فريق"},
  one:{en:"Online pharmacy that reads the prescription", ar:"صيدلية إلكترونية تقرأ الوصفة الطبية"},
  tags:{en:["Healthcare","Delivery","OCR"], ar:["صحة","توصيل","قراءة ضوئية"]},
  stats:[{v:"10K+", l:{en:"downloads",ar:"تحميل"}},{v:"4.6★", l:{en:"store rating",ar:"تقييم المتجر"}},{v:"3", l:{en:"devs led",ar:"مطورين بقيادتي"}}],
  body:{en:"Customers photograph a handwritten prescription and the app reads it. I led three developers on this. The reading pipeline decided whether the product worked at all.",
        ar:"يصوّر العميل وصفة مكتوبة بخط اليد، فيقرأها التطبيق. قدتُ ثلاثة مطورين في هذا المشروع. مسار القراءة هو ما يحدد نجاح المنتج من عدمه."},
  built:{en:["Prescription reading through the camera","Live order tracking","Medication reminders","Payment gateway and push notifications"],
         ar:["قراءة الوصفة الطبية بالكاميرا","تتبع الطلب لحظياً","تذكير بمواعيد الدواء","بوابة دفع وإشعارات"]},
  hard:{en:"Handwriting. Images get pre-processed before reading. A human confirms every order. A wrong medicine is not a shippable bug.",
        ar:"الخط اليدوي. الصورة تُعالج قبل القراءة. ثم تأكيد بشري قبل تمرير الطلب. دواء خاطئ ليس خطأً يُطلق ويُصلح لاحقاً."},
  tech:["Flutter","Firebase","OCR","Payment Gateway","Google Maps"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.adampharmacy"},{t:"ios",u:"https://apps.apple.com/app/id1672276218"}],
  icon:"https://play-lh.googleusercontent.com/r01GfpnAxEShNXIHee2gibLe-fMM56JBBQZhzcX22T0yQ1LQlA8w5EwNBZPtexzbpYI_mYVhLw0aGEODXRtB=w240",
  shots:["https://play-lh.googleusercontent.com/ZgpsLb3krfungshYUz_GoVqVu3RJ3OOKZQXGW-7cbjoDzRoU006S7Vwxqzuhg08Hp-jQTlFmL7YFNfANgonG=w1000",
"https://play-lh.googleusercontent.com/xGyl16_IxFC82fvxtE2RrcZF9916Zd-ZnuDobj6-Q6TPGBIRc5tdefzePtPXXFzaTvrcXdCmY-Q1ezjnNx5-iQ=w1000",
"https://play-lh.googleusercontent.com/OjEywH7XhKWhkLcKeiD0jzzDUPS33YnhspWsEeDZRFMXlmNqU6hnv6-UOgGOoc0WRjGSNskqf4MMPeHTNrYer0c=w1000",
"https://play-lh.googleusercontent.com/LiUQSIRyRxcB-YF39YJShyq7Qt6YpvH_geO9W0nSfvVCpT115NTr6amxQDDSoCHb-V1anTfTF-c_c3Tpu7awPGA=w1000",
"https://play-lh.googleusercontent.com/kL6JNt2LxRpK-cpE55jWVPaFzQmQTx3VXEGvpcTTTiWNl6o2HW8fRud7-1Y9-9jt1pq5rxczQGDbUHEsoPWY=w1000"] },

{ key:"bizbura", year:"2022", flag:"🇹🇷",
  name:{en:"BizBuradayız", ar:"بيز بورادايز"},
  role:{en:"Flutter Developer", ar:"مطور Flutter"},
  one:{en:"On-demand roadside assistance in Turkey", ar:"مساعدة على الطريق عند الطلب في تركيا"},
  tags:{en:["On-demand","Live tracking","Two apps"], ar:["خدمات عند الطلب","تتبع لحظي","تطبيقان"]},
  stats:[{v:"2", l:{en:"apps, one system",ar:"تطبيق في نظام واحد"}},{v:{en:"Live",ar:"لحظي"}, l:{en:"map tracking",ar:"تتبع على الخريطة"}}],
  body:{en:"Your car breaks down on a road in Turkey. You open the app and the nearest provider takes the job. You watch them come to you on the map.",
        ar:"تتعطل سيارتك على طريق في تركيا، فتفتح التطبيق. يستلم أقرب مزوّد خدمة الطلب. وتتابعه على الخريطة حتى يصل إليك. تطبيق للعميل وآخر للمزوّد، على حالة واحدة."},
  built:{en:["One system across two apps","Instant matching to the nearest provider","Live location tracking on the map","In-app chat and real-time order updates","Photo reviews"],
         ar:["نظام واحد من تطبيقين","مطابقة فورية مع أقرب مزوّد خدمة","تتبع لحظي للموقع على الخريطة","محادثة داخل التطبيق وتحديثات فورية للطلب","تقييمات بالصور"]},
  hard:{en:"Two apps, one truth. A stale screen means someone is stranded on a hard shoulder. Pusher and a single state layer keep them in step.",
        ar:"تطبيقان ومصدر حقيقة واحد. شاشة متأخرة تعني شخصاً واقفاً على جانب الطريق. Pusher وطبقة حالة واحدة تُبقيهما متطابقين."},
  tech:["Flutter","BLoC","Pusher","Google Maps","Real-time Tracking"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.bizburadayiz",label:{en:"Customer app",ar:"تطبيق العميل"}},
         {t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.bizburadayiz.driver",label:{en:"Provider app",ar:"تطبيق مزود الخدمة"}}],
  icon:"https://play-lh.googleusercontent.com/V6df11qDA0Y-Wo1eY4KAbzd5QnGtC13OmHLRKN2sI-VMdWt_jG9v3gPVlljxFjsnMlyxbhI87FflayM76pnpcIM=w240",
  shots:["https://play-lh.googleusercontent.com/Q3BaS6DWURTUvmD8ikJKsHZnaQo6JBhEi2-7CVBqwjiSnWy6BxHyrI40Gg09T96CQNh3xqXJ2mFs6HsfkeWECw=w1000",
"https://play-lh.googleusercontent.com/QEwCQQwvwmeEjhqUBDrjWseSqrucIFbwvF1tRAN34PUgHiiUSf2NF_dYlmvn7khEgy_1MrQP-K_XIu5VeMQNCg=w1000",
"https://play-lh.googleusercontent.com/9mepB9E6CuC0OEQE5cpC6UXF5c-PzD4rHhSjGdZz95u4G61D6llqCGopZbCvPfcdHt6W42UkADza3G0ziD6v=w1000",
"https://play-lh.googleusercontent.com/DjzSxxpDKar6qLgWpg3enxPPQxI6GFO_sAc2FqyLBVE-4NvuLyp2qMLOMX5ijkUwfHGQlosGz3NL58MPQrJ35w=w1000",
"https://play-lh.googleusercontent.com/Xc4G7CXdwhV3XnGWjWRCaGgfZPtVhhkik86kdLMSihU6-xceHQUgwQ9MapYaToiBEzG9c6lX1B664YHNSNUJbQ=w1000",
"https://play-lh.googleusercontent.com/gcRVkt-yqmrU8E9uU-DonU8gE6QLus3IypAbHf3lTGxwVRoKqaNro0F2DnCldAWc18fKKPMYdUO2bu8cTDbsrw=w1000"] },

{ key:"alnasser", year:"2022", flag:"🇰🇼",
  name:{en:"ALNASSER", ar:"الناصر"},
  role:{en:"Flutter Developer", ar:"مطور Flutter"},
  one:{en:"Kuwaiti fashion and sports retail", ar:"متجر أزياء ورياضة كويتي"},
  tags:{en:["E-commerce","Loyalty","Deep linking"], ar:["متجر إلكتروني","نقاط ولاء","روابط عميقة"]},
  stats:[{v:"100K+", l:{en:"downloads",ar:"تحميل"}},{v:"50+", l:{en:"stores in Kuwait",ar:"فرع في الكويت"}},{v:"8", l:{en:"countries",ar:"دول"}}],
  body:{en:"More than 50 stores in Kuwait and seven other countries. Campaign links open the product itself, not the home screen. Loyalty points bring people back.",
        ar:"أكثر من ٥٠ فرعاً في الكويت، وحضور في ٧ دول أخرى. روابط الحملات تفتح المنتج مباشرة، لا الصفحة الرئيسية. ونقاط الولاء تعيد العميل."},
  built:{en:["Catalogue with advanced filters and a size guide","Loyalty points and member-only discounts","Multiple payment methods at checkout","Deep links for marketing campaigns"],
         ar:["كتالوج بفلترة متقدمة ودليل مقاسات","نقاط ولاء وخصومات للأعضاء","طرق دفع متعددة عند الشراء","روابط عميقة لحملات التسويق"]},
  hard:{en:"A campaign click has to open that exact product inside the app. It works whether the app is installed or not.",
        ar:"النقرة على إعلان الحملة تفتح المنتج نفسه داخل التطبيق. يعمل هذا سواء كان التطبيق مثبتاً أم لا."},
  tech:["Flutter","Provider","Deep Linking","Payment","Firebase Analytics"],
  links:[{t:"play",u:"https://play.google.com/store/apps/details?id=com.namaait.alnasser"}],
  icon:"https://play-lh.googleusercontent.com/UAh109EbkFdE4tJNM_oWhxwsRnX1TbdIxScZkWML5dTWEzSBRfkAnqetrr6uvR_i61pdIkrvLB9PwNs1bhV3wA=w240",
  shots:["https://play-lh.googleusercontent.com/67vbk5ytrzBWgFD_8Y4SEeGWeTo5jhDeK5HA9mVAwMFInmP9OE5Ur5cyUQkufikULSD62TY8oWXsMEx5A-bNjg=w1000",
"https://play-lh.googleusercontent.com/MJKb7bgO9eMAU-Ez_EB2ah7w5BSrgpdH9Phfrlu_wMwXz8naHhPxIWx7j_Au1nuiX-gGP2lcKDEuBltKygh6sA=w1000",
"https://play-lh.googleusercontent.com/7-uDohTXv5SZYApY3muJ5qNELez3wT4V2ck-DIP9zGlk4zdZ1OntfG24q3P5OYONt7be_Q1TOoFGNl-juBIszg=w1000",
"https://play-lh.googleusercontent.com/PQ0K-l75JtTZbd6YK0LPnBKUari3J9nNyzMBsy1qkAXFanRS_JACINgRWKSo6pH8AxazZGLcRb7yvY5l7igD=w1000",
"https://play-lh.googleusercontent.com/vVea8RTvThhk3us3cK3jwr7MXpgB0Mba5K0GqLpwA5ogeHmzjOpRwsUKqwOVLNcdyeZ451REiG1YICfqZcuq7jA=w1000"] },

{ key:"hr-portal", year:"2023", flag:"🇸🇦",
  name:{en:"Employee Self-Service Portal", ar:"بوابة الموظفين"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Self-service portal for employees", ar:"بوابة خدمة ذاتية للموظفين"},
  tags:{en:["HR","Biometric auth","Tablet + mobile"], ar:["موارد بشرية","دخول بالبصمة","جوال ولوحي"]},
  stats:[{v:{en:"Mobile + tablet",ar:"جوال ولوحي"}, l:{en:"one build",ar:"بناء واحد"}},{v:{en:"From scratch",ar:"من الصفر"}, l:{en:"built",ar:"بُني"}}],
  body:{en:"An HR app for a Saudi organisation. Staff handle leave, payroll, attendance and document requests themselves. One build covers phone and tablet. Written from scratch.",
        ar:"تطبيق موارد بشرية لجهة سعودية. يُنجز الموظف طلبات الإجازة والرواتب والحضور والمستندات بنفسه. بناء واحد يغطي الجوال والجهاز اللوحي. مبني من الصفر."},
  built:{en:["Clean architecture from the first line","One interface for phone and tablet","Face and fingerprint sign-in","Leave, payroll, attendance and document requests"],
         ar:["معمارية نظيفة من أول سطر","واجهة واحدة للجوال والجهاز اللوحي","دخول ببصمة الوجه والإصبع","إجازات ورواتب وحضور وطلبات مستندات"]},
  hard:{en:"Phone and tablet had to feel equally finished. That meant real responsive layout, not a stretched phone screen.",
        ar:"الجوال والجهاز اللوحي بالجودة نفسها. تصميم متجاوب حقيقي، لا شاشة جوال ممدودة."},
  tech:["Flutter","Clean Architecture","Biometric Auth","Secure Storage","l10n"],
  links:[], internal:true,
  icon:"", shots:[] },
{ key:"pm-tablet", year:"2023", flag:"🇸🇦",
  name:{en:"Project Management Platform", ar:"منصة إدارة مشاريع"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Project management for contracting firms", ar:"إدارة مشاريع لشركات المقاولات"},
  tags:{en:["Project management","Tablet-first","Offline"], ar:["إدارة مشاريع","اللوحي أولاً","دون اتصال"]},
  stats:[{v:{en:"Tablet-first",ar:"لوحي أولاً"}, l:{en:"designed for",ar:"مصممة له"}},{v:{en:"Offline",ar:"دون اتصال"}, l:{en:"works on site",ar:"تعمل في الموقع"}}],
  body:{en:"Built for contracting and engineering firms. Interactive Gantt charts and live collaboration. It keeps working offline on construction sites with no coverage. Designed for the tablet first.",
        ar:"مبنية لشركات المقاولات والهندسة. مخططات جانت تفاعلية وتعاون لحظي. تعمل دون اتصال في مواقع البناء بلا تغطية. مصممة للجهاز اللوحي أولاً."},
  built:{en:["Interactive Gantt charts","Live collaboration over WebSocket","Offline mode for construction sites","Project files and drawings management"],
         ar:["مخططات جانت تفاعلية","تعاون لحظي عبر WebSocket","وضع عمل دون اتصال في مواقع البناء","إدارة ملفات المشروع ومخططاته"]},
  hard:{en:"A Gantt chart with hundreds of tasks on a tablet. Keeping it smooth needed custom painting. No off-the-shelf library could do it.",
        ar:"مخطط جانت بمئات المهام على جهاز لوحي. بقاؤه سلساً تطلّب رسماً مخصصاً. المكتبات الجاهزة لم تكن كافية."},
  tech:["Flutter","Custom Widgets","WebSockets","Offline-first"],
  links:[], internal:true,
  icon:"", shots:[] },
{ key:"yseer", year:"2025", flag:"🇸🇦",
  name:{en:"Yseer", ar:"يسير"},
  role:{en:"Senior Flutter Developer", ar:"مطور Flutter أول"},
  one:{en:"Saudi ordering and delivery platform", ar:"منصة سعودية للطلب والتوصيل"},
  tags:{en:["Logistics","Real-time","Payments"], ar:["خدمات لوجستية","أحداث لحظية","مدفوعات"]},
  stats:[{v:{en:"Riyadh",ar:"الرياض"}, l:{en:"operating city",ar:"مدينة التشغيل"}},{v:{en:"Events",ar:"الأحداث"}, l:{en:"ordered, not raced",ar:"مرتبة لا متسابقة"}}],
  body:{en:"Ordering and delivery across Riyadh. Order state changes from several sources in the same moment. Documenting and sequencing the events stopped them colliding.",
        ar:"المنصة تعمل في الرياض. حالة الطلب تتغير من أكثر من مصدر في اللحظة نفسها. توثيق الأحداث وترتيبها هو ما أنهى التعارض."},
  built:{en:["Returns and financial transactions module","Real-time events documented over WebSocket and Pusher","Booking and order routes rebuilt"],
         ar:["وحدة المرتجعات والمعاملات المالية","توثيق الأحداث اللحظية على WebSocket و Pusher","إعادة بناء مسارات الحجز والطلبات"]},
  hard:{en:"Several sources write the same order state at once.",
        ar:"أكثر من مصدر يكتب حالة الطلب نفسه في الوقت نفسه."},
  tech:["Flutter","BLoC","REST","WebSocket / Pusher"],
  links:[], internal:true,
  icon:"", shots:[] }
];

/* Text specific to the apps page. Everything shared (name, profiles, bar,
   footer) lives in /assets/shell.js — do not restate any of it here. */
window.PAGE = {
  title:{en:"Ahmed ElFirgany — App Catalogue", ar:"أحمد الفرجاني — كتالوج التطبيقات"},
  tagline:{en:"Apps that shipped, and are still running.", ar:"تطبيقات أُطلقت فعلاً، وما زالت تعمل."},
  intro:{en:"15+ apps across five countries. 600K+ downloads on Google Play alone. Each one below shows what it does, the hard part, and a working link.",
         ar:"أكثر من ١٥ تطبيقاً في ٥ دول. وأكثر من ٦٠٠ ألف تحميل على Google Play وحده. كل تطبيق هنا: ما يفعله، والجزء الصعب فيه، ورابط يفتح الآن."},
  stats:[{v:"15+", l:{en:"apps",ar:"تطبيق"}},{v:"600K+", l:{en:"downloads",ar:"تحميل"}},
         {v:"5", l:{en:"countries",ar:"دول"}},{v:"5+", l:{en:"years",ar:"سنوات خبرة"}}],
  fine:{en:"Screenshots come from the public store listings.", ar:"اللقطات من صفحات المتاجر العامة."},
  cross:{
    eyebrow:{en:"The other half", ar:"النصف الآخر"},
    h:{en:"The games", ar:"الألعاب"},
    p:{en:"The apps above shipped. The games are where I push Flutter further. Real 3D on the GPU, real Box2D physics, both playable in your browser.",
       ar:"التطبيقات في الأعلى عمل أُطلق. الألعاب مساحة أدفع فيها Flutter إلى أبعد من حدوده. رسوم ثلاثية الأبعاد على بطاقة الرسوميات، وفيزياء Box2D حقيقية، تلعبها في متصفحك الآن."},
    btn:{en:"Open the games", ar:"افتح الألعاب"},
    to:"games"
  }
};
